(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("forest_top",
{ "compressionlevel":-1,
 "editorsettings":
    {
     "export":
        {
         "format":"js",
         "target":"forest_top.js"
        }
    },
 "height":60,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":5,
         "name":"Fixed",
         "objects":[
                {
                 "gid":7,
                 "height":598,
                 "id":26,
                 "name":"vertical_wall",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":14,
                 "x":276,
                 "y":598
                }, 
                {
                 "gid":11,
                 "height":86,
                 "id":59,
                 "name":"angled_wall_4",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":52,
                 "x":914,
                 "y":100.333
                }, 
                {
                 "gid":21,
                 "height":14,
                 "id":61,
                 "name":"horizontal_wall",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":598,
                 "x":388,
                 "y":14
                }, 
                {
                 "gid":21,
                 "height":14,
                 "id":62,
                 "name":"horizontal_wall",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":598,
                 "x":278,
                 "y":14
                }, 
                {
                 "gid":10,
                 "height":52,
                 "id":70,
                 "name":"angled_wall_3",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":52,
                 "x":854,
                 "y":407
                }, 
                {
                 "gid":30,
                 "height":24,
                 "id":92,
                 "name":"ball_catch_arrow",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":24,
                 "x":350,
                 "y":90
                }, 
                {
                 "gid":22,
                 "height":598,
                 "id":110,
                 "name":"chute_wall",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":34,
                 "x":966,
                 "y":597.5
                }, 
                {
                 "gid":22,
                 "height":598,
                 "id":111,
                 "name":"chute_wall",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":34,
                 "x":894,
                 "y":725
                }, 
                {
                 "gid":51,
                 "height":75,
                 "id":137,
                 "name":"habitrail_small_track",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":310,
                 "type":"habitrail",
                 "visible":true,
                 "width":42,
                 "x":348,
                 "y":552
                }, 
                {
                 "gid":6,
                 "height":195,
                 "id":168,
                 "name":"drain_wall_right",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":197,
                 "x":698.5,
                 "y":680
                }, 
                {
                 "gid":51,
                 "height":75,
                 "id":170,
                 "name":"habitrail_small_track",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":0,
                 "type":"habitrail",
                 "visible":true,
                 "width":42,
                 "x":291,
                 "y":503
                }, 
                {
                 "gid":51,
                 "height":75,
                 "id":171,
                 "name":"habitrail_small_track",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":0,
                 "type":"habitrail",
                 "visible":true,
                 "width":42,
                 "x":291,
                 "y":427.5
                }, 
                {
                 "gid":51,
                 "height":75,
                 "id":172,
                 "name":"habitrail_small_track",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":0,
                 "type":"habitrail",
                 "visible":true,
                 "width":42,
                 "x":291,
                 "y":352
                }, 
                {
                 "gid":50,
                 "height":75,
                 "id":173,
                 "name":"habitrail_gateway",
                 "properties":[
                        {
                         "name":"relatedCollisionObjects",
                         "type":"string",
                         "value":"132,133"
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":310,
                 "type":"habitrail",
                 "visible":true,
                 "width":42,
                 "x":405,
                 "y":600
                }, 
                {
                 "gid":51,
                 "height":75,
                 "id":174,
                 "name":"habitrail_gateway",
                 "properties":[
                        {
                         "name":"relatedCollisionObjects",
                         "type":"string",
                         "value":"132,133"
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":0,
                 "type":"habitrail",
                 "visible":true,
                 "width":42,
                 "x":291,
                 "y":276.5
                }, 
                {
                 "gid":49,
                 "height":600,
                 "id":212,
                 "name":"forest_top_bg",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-100
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":false,
                 "width":720,
                 "x":277.634695876748,
                 "y":600.115771662659
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":4,
         "name":"Dynamic",
         "objects":[
                {
                 "gid":2,
                 "height":124,
                 "id":14,
                 "name":"flipper_left",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"left_flipper",
                 "visible":true,
                 "width":170,
                 "x":339,
                 "y":526
                }, 
                {
                 "gid":3,
                 "height":124,
                 "id":15,
                 "name":"flipper_right",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"right_flipper",
                 "visible":true,
                 "width":170,
                 "x":725,
                 "y":528
                }, 
                {
                 "gid":17,
                 "height":186,
                 "id":30,
                 "name":"flipper_bumper_left",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":55,
                 "x":334,
                 "y":405.5
                }, 
                {
                 "gid":18,
                 "height":186,
                 "id":31,
                 "name":"flipper_bumper_right",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":55,
                 "x":807.5,
                 "y":391
                }, 
                {
                 "gid":7,
                 "height":113,
                 "id":106,
                 "name":"plunger_gate",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"gate",
                 "visible":true,
                 "width":14,
                 "x":894,
                 "y":127
                }, 
                {
                 "gid":31,
                 "height":54,
                 "id":91,
                 "name":"ball_catch",
                 "properties":[
                        {
                         "name":"ball_catch",
                         "type":"object",
                         "value":149
                        }, 
                        {
                         "name":"score",
                         "type":"int",
                         "value":100
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"trigger",
                 "visible":true,
                 "width":54,
                 "x":307,
                 "y":78.6667
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":3,
         "name":"Collision",
         "objects":[
                {
                 "height":0,
                 "id":9,
                 "name":"flipper_bumper_left",
                 "polygon":[
                        {
                         "x":0.75,
                         "y":0.75
                        }, 
                        {
                         "x":0.25,
                         "y":134.75
                        }, 
                        {
                         "x":2.5,
                         "y":138.5
                        }, 
                        {
                         "x":46.3409,
                         "y":178.795
                        }, 
                        {
                         "x":55.8864,
                         "y":173.75
                        }, 
                        {
                         "x":19,
                         "y":-0.25
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":30
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":0,
                 "x":333,
                 "y":225.5
                }, 
                {
                 "height":0,
                 "id":53,
                 "name":"left",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-0.75,
                         "y":710.5
                        }, 
                        {
                         "x":13.25,
                         "y":710.25
                        }, 
                        {
                         "x":14,
                         "y":-0.5
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":276.5,
                 "y":0.5
                }, 
                {
                 "height":0,
                 "id":55,
                 "name":"flipper_bumper_right",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0.0909089,
                         "y":-131.727
                        }, 
                        {
                         "x":-18.4546,
                         "y":-134.09
                        }, 
                        {
                         "x":-54.3636,
                         "y":38.7273
                        }, 
                        {
                         "x":-44.4546,
                         "y":44.6364
                        }, 
                        {
                         "x":-2.18182,
                         "y":3.63636
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":31
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":0,
                 "x":862.273,
                 "y":344.455
                }, 
                {
                 "height":0,
                 "id":58,
                 "name":"right",
                 "polygon":[
                        {
                         "x":-73.6667,
                         "y":14.5
                        }, 
                        {
                         "x":-21.4868,
                         "y":99.876
                        }, 
                        {
                         "x":-19.8333,
                         "y":726.833
                        }, 
                        {
                         "x":12.6667,
                         "y":730.333
                        }, 
                        {
                         "x":14.1667,
                         "y":14
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":986.333,
                 "y":0
                }, 
                {
                 "height":0,
                 "id":60,
                 "name":"inner_right",
                 "polygon":[
                        {
                         "x":20,
                         "y":-1
                        }, 
                        {
                         "x":-14,
                         "y":0.843096
                        }, 
                        {
                         "x":-13.9419,
                         "y":240.582
                        }, 
                        {
                         "x":-58.3958,
                         "y":283.151
                        }, 
                        {
                         "x":-14.1571,
                         "y":282.856
                        }, 
                        {
                         "x":-14.3633,
                         "y":359.664
                        }, 
                        {
                         "x":-128.645,
                         "y":472.663
                        }, 
                        {
                         "x":-15,
                         "y":596.912
                        }, 
                        {
                         "x":19,
                         "y":597.333
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":908.333,
                 "y":127.333
                }, 
                {
                 "height":0,
                 "id":63,
                 "name":"top",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-664.333,
                         "y":0.333333
                        }, 
                        {
                         "x":-664.333,
                         "y":13.3333
                        }, 
                        {
                         "x":4.66667,
                         "y":14
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":940,
                 "y":0
                }, 
                {
                 "height":0,
                 "id":64,
                 "name":"flipper_right",
                 "polygon":[
                        {
                         "x":-9.52084,
                         "y":4.91666
                        }, 
                        {
                         "x":-132.414,
                         "y":104.016
                        }, 
                        {
                         "x":-117.515,
                         "y":122.788
                        }, 
                        {
                         "x":23.8484,
                         "y":51.7273
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":15
                        }],
                 "rotation":0,
                 "type":"flipper",
                 "visible":true,
                 "width":0,
                 "x":860.219,
                 "y":403.677
                }, 
                {
                 "ellipse":true,
                 "height":24,
                 "id":65,
                 "name":"flipper_right",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":15
                        }],
                 "rotation":0,
                 "type":"flipper_tip",
                 "visible":true,
                 "width":24,
                 "x":722.348,
                 "y":504.303
                }, 
                {
                 "ellipse":true,
                 "height":55,
                 "id":66,
                 "name":"flipper_right",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":15
                        }],
                 "rotation":0,
                 "type":"flipper_base",
                 "visible":true,
                 "width":55,
                 "x":839.015,
                 "y":403.636
                }, 
                {
                 "height":0,
                 "id":67,
                 "name":"flipper_left",
                 "polygon":[
                        {
                         "x":2.20833,
                         "y":-1.875
                        }, 
                        {
                         "x":-123.303,
                         "y":-102.575
                        }, 
                        {
                         "x":-154.242,
                         "y":-54.5455
                        }, 
                        {
                         "x":-11.8485,
                         "y":16.2727
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":14
                        }],
                 "rotation":0,
                 "type":"flipper",
                 "visible":true,
                 "width":0,
                 "x":505.234,
                 "y":507.584
                }, 
                {
                 "ellipse":true,
                 "height":24,
                 "id":68,
                 "name":"flipper_left",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":14
                        }],
                 "rotation":0,
                 "type":"flipper_tip",
                 "visible":true,
                 "width":24,
                 "x":486.416,
                 "y":501.917
                }, 
                {
                 "ellipse":true,
                 "height":55,
                 "id":69,
                 "name":"flipper_left",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":14
                        }],
                 "rotation":0,
                 "type":"flipper_base",
                 "visible":true,
                 "width":55,
                 "x":339.584,
                 "y":401.417
                }, 
                {
                 "height":0,
                 "id":73,
                 "name":"flipper_left",
                 "polygon":[
                        {
                         "x":-2.91667,
                         "y":10.25
                        }, 
                        {
                         "x":-107.303,
                         "y":-67.075
                        }, 
                        {
                         "x":-123.492,
                         "y":-42.0455
                        }, 
                        {
                         "x":-16.3485,
                         "y":11.2727
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":14
                        }],
                 "rotation":0,
                 "type":"flipper_inner",
                 "visible":true,
                 "width":0,
                 "x":505.75,
                 "y":505.5
                }, 
                {
                 "height":0,
                 "id":74,
                 "name":"flipper_right",
                 "polygon":[
                        {
                         "x":-35.6667,
                         "y":58.0833
                        }, 
                        {
                         "x":-126.456,
                         "y":124.766
                        }, 
                        {
                         "x":-116.182,
                         "y":128.121
                        }, 
                        {
                         "x":-17.9849,
                         "y":77.144
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":15
                        }],
                 "rotation":0,
                 "type":"flipper_inner",
                 "visible":true,
                 "width":0,
                 "x":856,
                 "y":393.75
                }, 
                {
                 "ellipse":true,
                 "height":40,
                 "id":131,
                 "name":"habitrail_gateway",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":136
                        }],
                 "rotation":319.588,
                 "type":"",
                 "visible":true,
                 "width":40,
                 "x":381.779,
                 "y":574.468
                }, 
                {
                 "height":0,
                 "id":132,
                 "name":"habitrail",
                 "polygon":[
                        {
                         "x":-32,
                         "y":385.5
                        }, 
                        {
                         "x":-143.333,
                         "y":289.667
                        }, 
                        {
                         "x":-143.5,
                         "y":-25.5
                        }, 
                        {
                         "x":-141.5,
                         "y":-13
                        }, 
                        {
                         "x":-141,
                         "y":286.167
                        }, 
                        {
                         "x":-27.6667,
                         "y":380.5
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":435,
                 "y":215.667
                }, 
                {
                 "height":0,
                 "id":133,
                 "name":"habitrail",
                 "polygon":[
                        {
                         "x":-40,
                         "y":380.5
                        }, 
                        {
                         "x":-136.5,
                         "y":296.5
                        }, 
                        {
                         "x":-138.333,
                         "y":10.7917
                        }, 
                        {
                         "x":-141.833,
                         "y":13.5
                        }, 
                        {
                         "x":-141.167,
                         "y":297.333
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":471.333,
                 "y":188
                }, 
                {
                 "height":0,
                 "id":135,
                 "name":"plunger_gate",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0.666667,
                         "y":112
                        }, 
                        {
                         "x":15.3333,
                         "y":112
                        }, 
                        {
                         "x":14.6667,
                         "y":-0.666667
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":106
                        }],
                 "rotation":0,
                 "type":"gate",
                 "visible":true,
                 "width":0,
                 "x":894,
                 "y":13
                }, 
                {
                 "ellipse":true,
                 "height":19,
                 "id":145,
                 "name":"flipper_bumper_left",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":30
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":19,
                 "x":333.75,
                 "y":219
                }, 
                {
                 "ellipse":true,
                 "height":12,
                 "id":146,
                 "name":"flipper_bumper_left",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":30
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":12,
                 "x":376.75,
                 "y":393.25
                }, 
                {
                 "ellipse":true,
                 "height":19,
                 "id":147,
                 "name":"flipper_bumper_right",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":31
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":19,
                 "x":843.25,
                 "y":204.25
                }, 
                {
                 "ellipse":true,
                 "height":12,
                 "id":148,
                 "name":"flipper_bumper_right",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":31
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":12,
                 "x":807.636,
                 "y":378.818
                }, 
                {
                 "ellipse":true,
                 "height":30,
                 "id":149,
                 "name":"ball_catch",
                 "properties":[
                        {
                         "name":"catcher",
                         "type":"bool",
                         "value":true
                        }, 
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":91
                        }],
                 "rotation":0,
                 "type":"trigger",
                 "visible":true,
                 "width":30,
                 "x":318.333,
                 "y":35.6667
                }, 
                {
                 "ellipse":true,
                 "height":40,
                 "id":163,
                 "name":"habitrail_gateway",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":142
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":40,
                 "x":291.607,
                 "y":189.394
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":6,
 "nextobjectid":213,
 "orientation":"orthogonal",
 "properties":[
        {
         "name":"maxY",
         "type":"int",
         "value":600
        }, 
        {
         "name":"minY",
         "type":"int",
         "value":0
        }],
 "renderorder":"right-down",
 "tiledversion":"1.4.3",
 "tileheight":10,
 "tilesets":[
        {
         "columns":0,
         "firstgid":1,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"dynamic",
         "spacing":0,
         "tilecount":24,
         "tileheight":600,
         "tiles":[
                {
                 "id":0,
                 "image":"..\/raw\/img\/backgrounds\/plunger.png",
                 "imageheight":289,
                 "imagewidth":68,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"plunger"
                }, 
                {
                 "id":1,
                 "image":"..\/raw\/img\/backgrounds\/flipper_left.png",
                 "imageheight":124,
                 "imagewidth":170,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"left_flipper"
                }, 
                {
                 "id":2,
                 "image":"..\/raw\/img\/backgrounds\/flipper_right.png",
                 "imageheight":124,
                 "imagewidth":170,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"right_flipper"
                }, 
                {
                 "id":3,
                 "image":"..\/img\/tables\/plunger_chute.png",
                 "imageheight":600,
                 "imagewidth":105,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":4,
                 "image":"..\/raw\/img\/backgrounds\/drain_wall_left.png",
                 "imageheight":195,
                 "imagewidth":197,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":5,
                 "image":"..\/raw\/img\/backgrounds\/drain_wall_right.png",
                 "imageheight":195,
                 "imagewidth":197,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":6,
                 "image":"..\/img\/tables\/vertical_wall.png",
                 "imageheight":600,
                 "imagewidth":14,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":7,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_1.png",
                 "imageheight":86,
                 "imagewidth":52,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":8,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_2.png",
                 "imageheight":52,
                 "imagewidth":52,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":9,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_3.png",
                 "imageheight":52,
                 "imagewidth":52,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":10,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_4.png",
                 "imageheight":86,
                 "imagewidth":52,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":11,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_yellow.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"circle_bumper"
                }, 
                {
                 "id":12,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_green.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"circle_bumper"
                }, 
                {
                 "id":13,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_blue.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"circle_bumper"
                }, 
                {
                 "id":14,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_red.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"circle_bumper"
                }, 
                {
                 "id":15,
                 "image":"..\/raw\/img\/backgrounds\/ball.png",
                 "imageheight":26,
                 "imagewidth":26,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":50
                        }],
                 "type":"ball"
                }, 
                {
                 "id":16,
                 "image":"..\/raw\/img\/backgrounds\/flipper_bumper_left.png",
                 "imageheight":186,
                 "imagewidth":55,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"flipper_bumper"
                }, 
                {
                 "id":17,
                 "image":"..\/raw\/img\/backgrounds\/flipper_bumper_right.png",
                 "imageheight":186,
                 "imagewidth":55,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"flipper_bumper"
                }, 
                {
                 "id":18,
                 "image":"..\/raw\/img\/backgrounds\/drain_rail_left.png",
                 "imageheight":270,
                 "imagewidth":82,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":19,
                 "image":"..\/raw\/img\/backgrounds\/drain_rail_right.png",
                 "imageheight":270,
                 "imagewidth":82,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":20,
                 "image":"..\/img\/tables\/horizontal_wall.png",
                 "imageheight":14,
                 "imagewidth":598,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":21,
                 "image":"..\/img\/tables\/chute_wall.png",
                 "imageheight":598,
                 "imagewidth":34,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":22,
                 "image":"..\/img\/tables\/slot.png",
                 "imageheight":45,
                 "imagewidth":31,
                 "type":"slot_machine"
                }, 
                {
                 "id":23,
                 "image":"..\/img\/tables\/lane_trigger.png",
                 "imageheight":26,
                 "imagewidth":5,
                 "type":"trigger"
                }],
         "tilewidth":598
        }, 
        {
         "columns":0,
         "firstgid":25,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"cloud_bg_top",
         "spacing":0,
         "tilecount":25,
         "tileheight":600,
         "tiles":[
                {
                 "id":0,
                 "image":"..\/raw\/img\/backgrounds\/cloud_bg_top.png",
                 "imageheight":600,
                 "imagewidth":720,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-100
                        }]
                }, 
                {
                 "id":1,
                 "image":"..\/img\/tables\/plane_red.png",
                 "imageheight":48,
                 "imagewidth":51,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":25
                        }]
                }, 
                {
                 "id":2,
                 "image":"..\/img\/tables\/plane_blue.png",
                 "imageheight":48,
                 "imagewidth":51,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":25
                        }]
                }, 
                {
                 "id":3,
                 "image":"..\/img\/tables\/plane_green.png",
                 "imageheight":48,
                 "imagewidth":51,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":25
                        }]
                }, 
                {
                 "id":4,
                 "image":"..\/img\/tables\/plane_yellow.png",
                 "imageheight":48,
                 "imagewidth":51,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":25
                        }]
                }, 
                {
                 "id":5,
                 "image":"..\/img\/tables\/ball_catch_arrow.png",
                 "imageheight":24,
                 "imagewidth":24,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":6,
                 "image":"..\/img\/tables\/ball_catch.png",
                 "imageheight":54,
                 "imagewidth":54,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":7,
                 "image":"..\/img\/tables\/plane_pipe_right.png",
                 "imageheight":54,
                 "imagewidth":39,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":30
                        }]
                }, 
                {
                 "id":8,
                 "image":"..\/img\/tables\/plane_pipe_left.png",
                 "imageheight":54,
                 "imagewidth":39,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":30
                        }]
                }, 
                {
                 "id":9,
                 "image":"..\/img\/tables\/circle_bumper_small_red.png",
                 "imageheight":54,
                 "imagewidth":54,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":10,
                 "image":"..\/img\/tables\/circle_bumper_small_yellow.png",
                 "imageheight":54,
                 "imagewidth":54,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":11,
                 "image":"..\/img\/tables\/circle_bumper_small_blue.png",
                 "imageheight":54,
                 "imagewidth":54,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":12,
                 "image":"..\/img\/tables\/circle_bumper_small_green.png",
                 "imageheight":54,
                 "imagewidth":54,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":13,
                 "image":"..\/img\/tables\/cyclone.png",
                 "imageheight":96,
                 "imagewidth":96,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":14,
                 "image":"..\/img\/tables\/cloud_1.png",
                 "imageheight":78,
                 "imagewidth":108,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":15,
                 "image":"..\/img\/tables\/cloud_2.png",
                 "imageheight":36,
                 "imagewidth":51,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":15
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":16,
                 "image":"..\/img\/tables\/cloud_3.png",
                 "imageheight":54,
                 "imagewidth":81,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":7
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":17,
                 "image":"..\/img\/tables\/cloud_4.png",
                 "imageheight":66,
                 "imagewidth":108,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":18,
                 "image":"..\/img\/tables\/cloud_5.png",
                 "imageheight":39,
                 "imagewidth":66,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":19,
                 "image":"..\/img\/tables\/cloud_bg_top_empty.png",
                 "imageheight":600,
                 "imagewidth":720,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-100
                        }]
                }, 
                {
                 "id":20,
                 "image":"..\/img\/tables\/spawner_plane.png",
                 "imageheight":54,
                 "imagewidth":54,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":21,
                 "image":"..\/img\/tables\/tiny_star.png",
                 "imageheight":1,
                 "imagewidth":1,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"star"
                }, 
                {
                 "id":22,
                 "image":"..\/img\/tables\/small_star.png",
                 "imageheight":5,
                 "imagewidth":5,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"star"
                }, 
                {
                 "id":23,
                 "image":"..\/img\/tables\/Planet.png",
                 "imageheight":128,
                 "imagewidth":128,
                 "properties":[
                        {
                         "name":"speed",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-75
                        }],
                 "type":"saturn"
                }, 
                {
                 "id":24,
                 "image":"..\/img\/tables\/forest_top_bg.png",
                 "imageheight":600,
                 "imagewidth":720
                }],
         "tilewidth":720
        }, 
        {
         "columns":0,
         "firstgid":50,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"habitrail",
         "spacing":0,
         "tilecount":3,
         "tileheight":125,
         "tiles":[
                {
                 "id":0,
                 "image":"..\/img\/tables\/habitrail_gateway.png",
                 "imageheight":75,
                 "imagewidth":42,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "type":"habitrail"
                }, 
                {
                 "id":1,
                 "image":"..\/img\/tables\/habitrail_small_track.png",
                 "imageheight":75,
                 "imagewidth":42,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "type":"habitrail"
                }, 
                {
                 "id":2,
                 "image":"..\/img\/tables\/habitrail_track.png",
                 "imageheight":125,
                 "imagewidth":42,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "type":"habitrail"
                }],
         "tilewidth":42
        }],
 "tilewidth":10,
 "type":"map",
 "version":1.4,
 "width":100
});