(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("forest",
{ "compressionlevel":-1,
 "editorsettings":
    {
     "export":
        {
         "format":"js",
         "target":"forest.js"
        }
    },
 "height":60,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":5,
         "name":"Fixed",
         "objects":[
                {
                 "gid":59,
                 "height":600,
                 "id":174,
                 "name":"forest_bottom_bg",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-100
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":false,
                 "width":720,
                 "x":276.069,
                 "y":602.989
                }, 
                {
                 "gid":43,
                 "height":600,
                 "id":175,
                 "name":"forest_vertical_wall",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":36,
                 "x":253.499,
                 "y":600.369
                }, 
                {
                 "gid":44,
                 "height":180,
                 "id":176,
                 "name":"forest_drain_wall_left",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":132,
                 "x":289.039,
                 "y":601.406
                }, 
                {
                 "gid":45,
                 "height":132,
                 "id":177,
                 "name":"forest_drain_wall_right",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":132,
                 "x":762.627,
                 "y":600.164
                }, 
                {
                 "gid":47,
                 "height":600,
                 "id":178,
                 "name":"forest_plunger_chute",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":198,
                 "x":817.396,
                 "y":599.747
                }, 
                {
                 "gid":48,
                 "height":132,
                 "id":179,
                 "name":"forest_angled_wall_5",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":138,
                 "x":288,
                 "y":57.6667
                }, 
                {
                 "gid":49,
                 "height":132,
                 "id":180,
                 "name":"forest_angled_wall_6",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":138,
                 "x":755.182,
                 "y":49.0909
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":4,
         "name":"Dynamic",
         "objects":[
                {
                 "gid":1,
                 "height":255,
                 "id":13,
                 "name":"plunger",
                 "properties":[
                        {
                         "name":"stop",
                         "type":"int",
                         "value":480
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"plunger",
                 "visible":true,
                 "width":30,
                 "x":930,
                 "y":550
                }, 
                {
                 "gid":2,
                 "height":124,
                 "id":14,
                 "name":"flipper_left",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"left_flipper",
                 "visible":true,
                 "width":170,
                 "x":386,
                 "y":592
                }, 
                {
                 "gid":3,
                 "height":124,
                 "id":15,
                 "name":"flipper_right",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"right_flipper",
                 "visible":true,
                 "width":170,
                 "x":631,
                 "y":593
                }, 
                {
                 "gid":16,
                 "height":26,
                 "id":16,
                 "name":"ball",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":50
                        }],
                 "rotation":0,
                 "type":"ball",
                 "visible":true,
                 "width":26,
                 "x":931.667,
                 "y":290.333
                }, 
                {
                 "gid":23,
                 "height":13.5454,
                 "id":73,
                 "name":"rotating_gate",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":75
                        }],
                 "rotation":0,
                 "type":"rotating_gate",
                 "visible":true,
                 "width":26.5455,
                 "x":343.091,
                 "y":333.727
                }, 
                {
                 "gid":21,
                 "height":5.51376,
                 "id":92,
                 "name":"light_trigger",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"targ_light",
                         "type":"object",
                         "value":91
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"trigger",
                 "visible":true,
                 "width":2.68293,
                 "x":570.959,
                 "y":130
                }, 
                {
                 "gid":21,
                 "height":5.51,
                 "id":94,
                 "name":"light_trigger",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"targ_light",
                         "type":"object",
                         "value":90
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"trigger",
                 "visible":true,
                 "width":2.68293,
                 "x":604.323,
                 "y":130
                }, 
                {
                 "gid":21,
                 "height":5.51,
                 "id":97,
                 "name":"light_trigger",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"targ_light",
                         "type":"object",
                         "value":89
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"trigger",
                 "visible":true,
                 "width":2.68293,
                 "x":637.323,
                 "y":130
                }, 
                {
                 "gid":26,
                 "height":24,
                 "id":89,
                 "name":"letter_light",
                 "properties":[
                        {
                         "name":"bonus",
                         "type":"object",
                         "value":119
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"letter_light",
                 "visible":true,
                 "width":24,
                 "x":627.333,
                 "y":123
                }, 
                {
                 "gid":26,
                 "height":24,
                 "id":90,
                 "name":"letter_light",
                 "properties":[
                        {
                         "name":"bonus",
                         "type":"object",
                         "value":119
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"letter_light",
                 "visible":true,
                 "width":24,
                 "x":594,
                 "y":123.333
                }, 
                {
                 "gid":26,
                 "height":24,
                 "id":91,
                 "name":"letter_light",
                 "properties":[
                        {
                         "name":"bonus",
                         "type":"object",
                         "value":119
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"letter_light",
                 "visible":true,
                 "width":24,
                 "x":561.333,
                 "y":123
                }, 
                {
                 "gid":21,
                 "height":5.51,
                 "id":103,
                 "name":"light_trigger",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"targ_light",
                         "type":"object",
                         "value":104
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"trigger",
                 "visible":true,
                 "width":2.68293,
                 "x":538.073,
                 "y":130.375
                }, 
                {
                 "gid":26,
                 "height":24,
                 "id":104,
                 "name":"letter_light",
                 "properties":[
                        {
                         "name":"bonus",
                         "type":"object",
                         "value":119
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"letter_light",
                 "visible":true,
                 "width":24,
                 "x":528.083,
                 "y":123.375
                }, 
                {
                 "gid":35,
                 "height":24,
                 "id":119,
                 "name":"bonus_light_2x",
                 "properties":[
                        {
                         "name":"bonusMult",
                         "type":"int",
                         "value":2
                        }, 
                        {
                         "name":"bonusTime",
                         "type":"int",
                         "value":60
                        }, 
                        {
                         "name":"requiredLights",
                         "type":"int",
                         "value":4
                        }],
                 "rotation":0,
                 "type":"status_light",
                 "visible":true,
                 "width":24,
                 "x":572.636,
                 "y":399.364
                }, 
                {
                 "gid":23,
                 "height":13.5454,
                 "id":121,
                 "name":"rotating_gate",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":75
                        }],
                 "rotation":0,
                 "type":"rotating_gate",
                 "visible":true,
                 "width":26.5455,
                 "x":802.727,
                 "y":334.227
                }, 
                {
                 "gid":50,
                 "height":270,
                 "id":181,
                 "name":"forest_drain_rail_left",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":78,
                 "x":325,
                 "y":507
                }, 
                {
                 "gid":51,
                 "height":270,
                 "id":183,
                 "name":"forest_drain_rail_right",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":78,
                 "x":775.5,
                 "y":517
                }, 
                {
                 "gid":53,
                 "height":186,
                 "id":185,
                 "name":"forest_flipper_bumper_left",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":57,
                 "x":374.262109663142,
                 "y":430.349397590361
                }, 
                {
                 "gid":54,
                 "height":186,
                 "id":186,
                 "name":"forest_flipper_bumper_right",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":57,
                 "x":748.001967051881,
                 "y":441.168182935825
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":3,
         "name":"Collision",
         "objects":[
                {
                 "height":0,
                 "id":9,
                 "name":"flipper_bumper_left",
                 "polygon":[
                        {
                         "x":0.75,
                         "y":3.76136
                        }, 
                        {
                         "x":0.875,
                         "y":134.75
                        }, 
                        {
                         "x":3.875,
                         "y":138.375
                        }, 
                        {
                         "x":45.25,
                         "y":178.125
                        }, 
                        {
                         "x":55.25,
                         "y":172.75
                        }, 
                        {
                         "x":19.3636,
                         "y":0.659091
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":185
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":0,
                 "x":372,
                 "y":250.5
                }, 
                {
                 "height":0,
                 "id":41,
                 "name":"plunger",
                 "polygon":[
                        {
                         "x":17.75,
                         "y":46.7727
                        }, 
                        {
                         "x":17.75,
                         "y":59.5
                        }, 
                        {
                         "x":47.75,
                         "y":59.5
                        }, 
                        {
                         "x":47.75,
                         "y":46.7727
                        }, 
                        {
                         "x":37.75,
                         "y":46.7727
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":13
                        }],
                 "rotation":0,
                 "type":"plunger",
                 "visible":true,
                 "width":0,
                 "x":912,
                 "y":248.25
                }, 
                {
                 "height":0,
                 "id":42,
                 "name":"flipper_left",
                 "polygon":[
                        {
                         "x":0.855069,
                         "y":-2.47826
                        }, 
                        {
                         "x":-125.261,
                         "y":-103.325
                        }, 
                        {
                         "x":-154.992,
                         "y":-56.4205
                        }, 
                        {
                         "x":-11.8485,
                         "y":16.2727
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":14
                        }],
                 "rotation":0,
                 "type":"flipper",
                 "visible":true,
                 "width":0,
                 "x":550.485,
                 "y":575.667
                }, 
                {
                 "height":0,
                 "id":43,
                 "name":"flipper_right",
                 "polygon":[
                        {
                         "x":-10.9394,
                         "y":7.30302
                        }, 
                        {
                         "x":-132.006,
                         "y":103.4
                        }, 
                        {
                         "x":-120.515,
                         "y":123.455
                        }, 
                        {
                         "x":21.8484,
                         "y":51.394
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":15
                        }],
                 "rotation":0,
                 "type":"flipper",
                 "visible":true,
                 "width":0,
                 "x":767.545,
                 "y":469.333
                }, 
                {
                 "ellipse":true,
                 "height":26,
                 "id":45,
                 "name":"ball",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":16
                        }],
                 "rotation":0,
                 "type":"ball",
                 "visible":true,
                 "width":26,
                 "x":931.333,
                 "y":264.667
                }, 
                {
                 "height":0,
                 "id":50,
                 "name":"right",
                 "polygon":[
                        {
                         "x":1,
                         "y":60
                        }, 
                        {
                         "x":-135.5,
                         "y":195
                        }, 
                        {
                         "x":107.5,
                         "y":194.5
                        }, 
                        {
                         "x":103.736,
                         "y":-484
                        }, 
                        {
                         "x":70.236,
                         "y":-484.5
                        }, 
                        {
                         "x":70.3182,
                         "y":147.682
                        }, 
                        {
                         "x":34.9091,
                         "y":147.318
                        }, 
                        {
                         "x":34.986,
                         "y":-484
                        }, 
                        {
                         "x":-2.5,
                         "y":-569.223
                        }, 
                        {
                         "x":-135.5,
                         "y":-473
                        }, 
                        {
                         "x":0,
                         "y":-356
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":892.5,
                 "y":404.5
                }, 
                {
                 "height":0,
                 "id":51,
                 "name":"drain_rail_right",
                 "polygon":[
                        {
                         "x":1.66667,
                         "y":-1.66667
                        }, 
                        {
                         "x":-10.5,
                         "y":1.16667
                        }, 
                        {
                         "x":-12.75,
                         "y":166.159
                        }, 
                        {
                         "x":-90.9546,
                         "y":227.909
                        }, 
                        {
                         "x":-50.7954,
                         "y":265.25
                        }, 
                        {
                         "x":-0.25,
                         "y":169.159
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":183
                        }],
                 "rotation":0,
                 "type":"drain_divider",
                 "visible":true,
                 "width":0,
                 "x":847.25,
                 "y":248.75
                }, 
                {
                 "height":0,
                 "id":52,
                 "name":"drain_rail_left",
                 "polygon":[
                        {
                         "x":0,
                         "y":-0.666667
                        }, 
                        {
                         "x":1.5,
                         "y":172.864
                        }, 
                        {
                         "x":62.7955,
                         "y":277.318
                        }, 
                        {
                         "x":96.9318,
                         "y":235.159
                        }, 
                        {
                         "x":15.4318,
                         "y":165.341
                        }, 
                        {
                         "x":14.8182,
                         "y":2.30303
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":181
                        }],
                 "rotation":0,
                 "type":"drain_divider",
                 "visible":true,
                 "width":0,
                 "x":328,
                 "y":237.182
                }, 
                {
                 "height":0,
                 "id":53,
                 "name":"left",
                 "polygon":[
                        {
                         "x":0,
                         "y":-80
                        }, 
                        {
                         "x":-1,
                         "y":599.5
                        }, 
                        {
                         "x":150.5,
                         "y":599.5
                        }, 
                        {
                         "x":14.5,
                         "y":465.5
                        }, 
                        {
                         "x":15,
                         "y":50.5
                        }, 
                        {
                         "x":152.5,
                         "y":-64
                        }, 
                        {
                         "x":0.0214,
                         "y":-150.419
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":276.5,
                 "y":0.5
                }, 
                {
                 "height":0,
                 "id":55,
                 "name":"flipper_bumper_right",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0.181818,
                         "y":-134.545
                        }, 
                        {
                         "x":-18.7273,
                         "y":-134.545
                        }, 
                        {
                         "x":-54.3636,
                         "y":38
                        }, 
                        {
                         "x":-44.9091,
                         "y":44
                        }, 
                        {
                         "x":-2.18182,
                         "y":3.63636
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":186
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":0,
                 "x":803.273,
                 "y":395.455
                }, 
                {
                 "ellipse":true,
                 "height":23,
                 "id":60,
                 "name":"flipper_right",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":15
                        }],
                 "rotation":0,
                 "type":"flipper_tip",
                 "visible":true,
                 "width":23,
                 "x":631.674,
                 "y":569.959
                }, 
                {
                 "ellipse":true,
                 "height":55,
                 "id":61,
                 "name":"flipper_right",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":15
                        }],
                 "rotation":0,
                 "type":"flipper_base",
                 "visible":true,
                 "width":55,
                 "x":746.341,
                 "y":470.292
                }, 
                {
                 "ellipse":true,
                 "height":23,
                 "id":62,
                 "name":"flipper_left",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":14
                        }],
                 "rotation":0,
                 "type":"flipper_tip",
                 "visible":true,
                 "width":23,
                 "x":531.667,
                 "y":570
                }, 
                {
                 "ellipse":true,
                 "height":55,
                 "id":63,
                 "name":"flipper_left",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":14
                        }],
                 "rotation":0,
                 "type":"flipper_base",
                 "visible":true,
                 "width":55,
                 "x":384.833,
                 "y":469.5
                }, 
                {
                 "height":0,
                 "id":66,
                 "name":"flipper_right",
                 "polygon":[
                        {
                         "x":-35.6667,
                         "y":58.0833
                        }, 
                        {
                         "x":-126.456,
                         "y":124.766
                        }, 
                        {
                         "x":-116.182,
                         "y":128.121
                        }, 
                        {
                         "x":-17.9849,
                         "y":77.144
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":15
                        }],
                 "rotation":0,
                 "type":"flipper_inner",
                 "visible":true,
                 "width":0,
                 "x":765,
                 "y":458.667
                }, 
                {
                 "height":0,
                 "id":67,
                 "name":"flipper_left",
                 "polygon":[
                        {
                         "x":-2.91667,
                         "y":10.25
                        }, 
                        {
                         "x":-107.303,
                         "y":-67.075
                        }, 
                        {
                         "x":-123.492,
                         "y":-42.0455
                        }, 
                        {
                         "x":-16.3485,
                         "y":11.2727
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":14
                        }],
                 "rotation":0,
                 "type":"flipper_inner",
                 "visible":true,
                 "width":0,
                 "x":551,
                 "y":575
                }, 
                {
                 "height":0,
                 "id":75,
                 "name":"rotating_gate",
                 "polygon":[
                        {
                         "x":-0.301653,
                         "y":-0.489669
                        }, 
                        {
                         "x":3.01653,
                         "y":-5.87603
                        }, 
                        {
                         "x":23.0764,
                         "y":-5.54959
                        }, 
                        {
                         "x":26.2438,
                         "y":0
                        }, 
                        {
                         "x":22.4731,
                         "y":8.4876
                        }, 
                        {
                         "x":3.31818,
                         "y":7.99793
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":73
                        }],
                 "rotation":0,
                 "type":"rotating_gate",
                 "visible":true,
                 "width":0,
                 "x":343.029,
                 "y":326.512
                }, 
                {
                 "ellipse":true,
                 "height":13.9513,
                 "id":93,
                 "name":"light_trigger",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":92
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":13.9513,
                 "x":566.203,
                 "y":120
                }, 
                {
                 "ellipse":true,
                 "height":13.9513,
                 "id":95,
                 "name":"light_trigger",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":94
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":13.9513,
                 "x":599.567,
                 "y":120
                }, 
                {
                 "ellipse":true,
                 "height":13.9513,
                 "id":96,
                 "name":"light_trigger",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":97
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":13.9513,
                 "x":632.567,
                 "y":120
                }, 
                {
                 "ellipse":true,
                 "height":13.9513,
                 "id":102,
                 "name":"light_trigger",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":103
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":13.9513,
                 "x":533.317,
                 "y":120.375
                }, 
                {
                 "ellipse":true,
                 "height":19,
                 "id":105,
                 "name":"flipper_bumper_left",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":185
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":19,
                 "x":372.667,
                 "y":244.417
                }, 
                {
                 "ellipse":true,
                 "height":12,
                 "id":106,
                 "name":"flipper_bumper_left",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":185
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":12,
                 "x":415.375,
                 "y":418
                }, 
                {
                 "ellipse":true,
                 "height":19,
                 "id":108,
                 "name":"flipper_bumper_right",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":186
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":19,
                 "x":784.167,
                 "y":254.5
                }, 
                {
                 "ellipse":true,
                 "height":12,
                 "id":109,
                 "name":"flipper_bumper_right",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":186
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":12,
                 "x":748.667,
                 "y":429
                }, 
                {
                 "height":0,
                 "id":120,
                 "name":"rotating_gate",
                 "polygon":[
                        {
                         "x":-0.301653,
                         "y":-0.489669
                        }, 
                        {
                         "x":3.01653,
                         "y":-5.87603
                        }, 
                        {
                         "x":23.0764,
                         "y":-5.54959
                        }, 
                        {
                         "x":26.2438,
                         "y":0
                        }, 
                        {
                         "x":22.4731,
                         "y":8.4876
                        }, 
                        {
                         "x":3.31818,
                         "y":7.99793
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":121
                        }],
                 "rotation":0,
                 "type":"rotating_gate",
                 "visible":true,
                 "width":0,
                 "x":803,
                 "y":326
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":7,
 "nextobjectid":187,
 "orientation":"orthogonal",
 "properties":[
        {
         "name":"maxY",
         "type":"int",
         "value":600
        }, 
        {
         "name":"minY",
         "type":"int",
         "value":0
        }],
 "renderorder":"right-down",
 "tiledversion":"1.4.3",
 "tileheight":10,
 "tilesets":[
        {
         "columns":0,
         "firstgid":1,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"dynamic",
         "spacing":0,
         "tilecount":52,
         "tileheight":600,
         "tiles":[
                {
                 "id":0,
                 "image":"..\/raw\/img\/backgrounds\/plunger.png",
                 "imageheight":289,
                 "imagewidth":68,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"plunger"
                }, 
                {
                 "id":1,
                 "image":"..\/img\/tables\/flipper_left.png",
                 "imageheight":126,
                 "imagewidth":171,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"left_flipper"
                }, 
                {
                 "id":2,
                 "image":"..\/img\/tables\/flipper_right.png",
                 "imageheight":126,
                 "imagewidth":171,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"right_flipper"
                }, 
                {
                 "id":3,
                 "image":"..\/img\/tables\/plunger_chute.png",
                 "imageheight":600,
                 "imagewidth":105,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":4,
                 "image":"..\/raw\/img\/backgrounds\/drain_wall_left.png",
                 "imageheight":195,
                 "imagewidth":197,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":5,
                 "image":"..\/raw\/img\/backgrounds\/drain_wall_right.png",
                 "imageheight":195,
                 "imagewidth":197,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":6,
                 "image":"..\/raw\/img\/backgrounds\/vertical_wall.png",
                 "imageheight":598,
                 "imagewidth":14,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":7,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_1.png",
                 "imageheight":86,
                 "imagewidth":52,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":8,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_2.png",
                 "imageheight":52,
                 "imagewidth":52,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":9,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_3.png",
                 "imageheight":52,
                 "imagewidth":52,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":10,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_4.png",
                 "imageheight":86,
                 "imagewidth":52,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":11,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_yellow.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"circle_bumper"
                }, 
                {
                 "id":12,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_green.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"circle_bumper"
                }, 
                {
                 "id":13,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_blue.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"circle_bumper"
                }, 
                {
                 "id":14,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_red.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"circle_bumper"
                }, 
                {
                 "id":15,
                 "image":"..\/raw\/img\/backgrounds\/ball.png",
                 "imageheight":26,
                 "imagewidth":26,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":50
                        }],
                 "type":"ball"
                }, 
                {
                 "id":16,
                 "image":"..\/raw\/img\/backgrounds\/flipper_bumper_left.png",
                 "imageheight":186,
                 "imagewidth":55,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"flipper_bumper"
                }, 
                {
                 "id":17,
                 "image":"..\/raw\/img\/backgrounds\/flipper_bumper_right.png",
                 "imageheight":186,
                 "imagewidth":55,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"flipper_bumper"
                }, 
                {
                 "id":18,
                 "image":"..\/raw\/img\/backgrounds\/drain_rail_left.png",
                 "imageheight":270,
                 "imagewidth":82,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":19,
                 "image":"..\/raw\/img\/backgrounds\/drain_rail_right.png",
                 "imageheight":270,
                 "imagewidth":82,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":20,
                 "image":"..\/raw\/img\/backgrounds\/lane_trigger.png",
                 "imageheight":26,
                 "imagewidth":5,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"trigger"
                }, 
                {
                 "id":22,
                 "image":"..\/raw\/img\/backgrounds\/rotating_gate_provisional.png",
                 "imageheight":9,
                 "imagewidth":20,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":75
                        }]
                }, 
                {
                 "id":23,
                 "image":"..\/img\/tables\/angled_wall_5.png",
                 "imageheight":142,
                 "imagewidth":140,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":24,
                 "image":"..\/img\/tables\/angled_wall_6.png",
                 "imageheight":142,
                 "imagewidth":140,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":25,
                 "image":"..\/img\/tables\/letter_light_unlit.png",
                 "imageheight":24,
                 "imagewidth":24,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":26,
                 "image":"..\/img\/tables\/letter_light_lit.png",
                 "imageheight":24,
                 "imagewidth":24,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":27,
                 "image":"..\/img\/tables\/cloud_1.png",
                 "imageheight":78,
                 "imagewidth":108,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":28,
                 "image":"..\/img\/tables\/cloud_2.png",
                 "imageheight":36,
                 "imagewidth":51,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":15
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":29,
                 "image":"..\/img\/tables\/cloud_3.png",
                 "imageheight":54,
                 "imagewidth":81,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":7
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":30,
                 "image":"..\/img\/tables\/cloud_4.png",
                 "imageheight":66,
                 "imagewidth":108,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":31,
                 "image":"..\/img\/tables\/cloud_5.png",
                 "imageheight":39,
                 "imagewidth":66,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":32,
                 "image":"..\/img\/tables\/cloud_6.png",
                 "imageheight":96,
                 "imagewidth":144,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":3
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":33,
                 "image":"..\/img\/tables\/cloud_7.png",
                 "imageheight":96,
                 "imagewidth":144,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":3
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":34,
                 "image":"..\/img\/tables\/2x_bonus_light_unlit.png",
                 "imageheight":24,
                 "imagewidth":24
                }, 
                {
                 "id":35,
                 "image":"..\/img\/tables\/tiny_star.png",
                 "imageheight":1,
                 "imagewidth":1,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"star"
                }, 
                {
                 "id":36,
                 "image":"..\/img\/tables\/small_star.png",
                 "imageheight":5,
                 "imagewidth":5,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"star"
                }, 
                {
                 "id":37,
                 "image":"..\/img\/tables\/expanding_star.png",
                 "imageheight":16,
                 "imagewidth":16
                }, 
                {
                 "id":38,
                 "image":"..\/img\/tables\/expanding_star_2.png",
                 "imageheight":20,
                 "imagewidth":20
                }, 
                {
                 "id":39,
                 "image":"..\/img\/tables\/rocket.png",
                 "imageheight":96,
                 "imagewidth":96,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-75
                        }],
                 "type":"rocket"
                }, 
                {
                 "id":40,
                 "image":"..\/img\/tables\/space_shuttle.png",
                 "imageheight":96,
                 "imagewidth":96,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-75
                        }],
                 "type":"shuttle"
                }, 
                {
                 "id":41,
                 "image":"..\/img\/tables\/sputniksatellite.png",
                 "imageheight":96,
                 "imagewidth":96,
                 "type":"sputnik"
                }, 
                {
                 "id":42,
                 "image":"..\/img\/tables\/forest_vertical_wall.png",
                 "imageheight":600,
                 "imagewidth":36
                }, 
                {
                 "id":43,
                 "image":"..\/img\/tables\/forest_drain_wall_left.png",
                 "imageheight":180,
                 "imagewidth":132
                }, 
                {
                 "id":44,
                 "image":"..\/img\/tables\/forest_drain_wall_right.png",
                 "imageheight":132,
                 "imagewidth":132
                }, 
                {
                 "id":46,
                 "image":"..\/img\/tables\/forest_plunger_chute.png",
                 "imageheight":600,
                 "imagewidth":198
                }, 
                {
                 "id":47,
                 "image":"..\/img\/tables\/forest_angled_wall_5.png",
                 "imageheight":132,
                 "imagewidth":138
                }, 
                {
                 "id":48,
                 "image":"..\/img\/tables\/forest_angled_wall_6.png",
                 "imageheight":132,
                 "imagewidth":138
                }, 
                {
                 "id":49,
                 "image":"..\/img\/tables\/forest_drain_rail_left.png",
                 "imageheight":270,
                 "imagewidth":78
                }, 
                {
                 "id":50,
                 "image":"..\/img\/tables\/forest_drain_rail_right.png",
                 "imageheight":270,
                 "imagewidth":78
                }, 
                {
                 "id":51,
                 "image":"..\/img\/tables\/forest_flipper_bumper_left.png",
                 "imageheight":186,
                 "imagewidth":54
                }, 
                {
                 "id":52,
                 "image":"..\/img\/tables\/forest_flipper_bumper_v2.png",
                 "imageheight":186,
                 "imagewidth":57
                }, 
                {
                 "id":53,
                 "image":"..\/img\/tables\/forest_flipper_bumper_right_v2.png",
                 "imageheight":186,
                 "imagewidth":57
                }],
         "tilewidth":198
        }, 
        {
         "columns":0,
         "firstgid":55,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"cloud_bg",
         "spacing":0,
         "tilecount":3,
         "tileheight":600,
         "tiles":[
                {
                 "id":0,
                 "image":"..\/raw\/img\/backgrounds\/cloud_bg.png",
                 "imageheight":600,
                 "imagewidth":720,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-100
                        }]
                }, 
                {
                 "id":1,
                 "image":"..\/img\/tables\/cloud_bg_top_empty.png",
                 "imageheight":600,
                 "imagewidth":720,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-100
                        }]
                }, 
                {
                 "id":4,
                 "image":"..\/raw\/img\/backgrounds\/forest_bottom_bg.png",
                 "imageheight":600,
                 "imagewidth":720
                }],
         "tilewidth":720
        }, 
        {
         "columns":0,
         "firstgid":60,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"habitrail",
         "spacing":0,
         "tilecount":3,
         "tileheight":125,
         "tiles":[
                {
                 "id":6,
                 "image":"..\/raw\/img\/backgrounds\/habitrail1.png",
                 "imageheight":75,
                 "imagewidth":36,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "type":"habitrail"
                }, 
                {
                 "id":7,
                 "image":"..\/raw\/img\/backgrounds\/habitrail2.png",
                 "imageheight":125,
                 "imagewidth":36,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "type":"habitrail"
                }, 
                {
                 "id":8,
                 "image":"..\/raw\/img\/backgrounds\/habitrail3.png",
                 "imageheight":75,
                 "imagewidth":36,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "type":"habitrail"
                }],
         "tilewidth":36
        }],
 "tilewidth":10,
 "type":"map",
 "version":1.4,
 "width":100
});