(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("prototype_short_flipper",
{ "compressionlevel":-1,
 "editorsettings":
    {
     "export":
        {
         "format":"js",
         "target":"prototype_short_flipper.js"
        }
    },
 "height":60,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":5,
         "name":"Fixed",
         "objects":[
                {
                 "gid":39,
                 "height":600,
                 "id":110,
                 "name":"cloud_bg_top_empty",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-100
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":false,
                 "width":720,
                 "x":276,
                 "y":599
                }, 
                {
                 "gid":4,
                 "height":598,
                 "id":23,
                 "name":"plunger_chute",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":105,
                 "x":893,
                 "y":598
                }, 
                {
                 "gid":6,
                 "height":195,
                 "id":24,
                 "name":"drain_wall_right",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":197,
                 "x":698,
                 "y":598
                }, 
                {
                 "gid":5,
                 "height":195,
                 "id":25,
                 "name":"drain_wall_left",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":197,
                 "x":289,
                 "y":598
                }, 
                {
                 "gid":7,
                 "height":598,
                 "id":26,
                 "name":"vertical_wall",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":14,
                 "x":276,
                 "y":598
                }, 
                {
                 "gid":24,
                 "height":142,
                 "id":78,
                 "name":"angled_wall_5",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":140,
                 "x":290.333,
                 "y":132
                }, 
                {
                 "gid":25,
                 "height":142,
                 "id":79,
                 "name":"angled_wall_6",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":140,
                 "x":752.667,
                 "y":132
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":4,
         "name":"Dynamic",
         "objects":[
                {
                 "gid":33,
                 "height":96,
                 "id":111,
                 "name":"cloud_6",
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":3
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "rotation":0,
                 "type":"cloud",
                 "visible":true,
                 "width":144,
                 "x":415,
                 "y":487
                }, 
                {
                 "gid":34,
                 "height":96,
                 "id":112,
                 "name":"cloud_7",
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":3
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "rotation":0,
                 "type":"cloud",
                 "visible":true,
                 "width":144,
                 "x":580,
                 "y":484
                }, 
                {
                 "gid":28,
                 "height":78,
                 "id":113,
                 "name":"cloud_1",
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "rotation":0,
                 "type":"cloud",
                 "visible":true,
                 "width":108,
                 "x":278,
                 "y":84
                }, 
                {
                 "gid":29,
                 "height":36,
                 "id":114,
                 "name":"cloud_2",
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":15
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "rotation":0,
                 "type":"cloud",
                 "visible":true,
                 "width":51,
                 "x":357,
                 "y":165
                }, 
                {
                 "gid":30,
                 "height":54,
                 "id":115,
                 "name":"cloud_3",
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":7
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "rotation":0,
                 "type":"cloud",
                 "visible":true,
                 "width":81,
                 "x":441,
                 "y":251
                }, 
                {
                 "gid":31,
                 "height":66,
                 "id":116,
                 "name":"cloud_4",
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "rotation":0,
                 "type":"cloud",
                 "visible":true,
                 "width":108,
                 "x":589,
                 "y":143
                }, 
                {
                 "gid":32,
                 "height":39,
                 "id":117,
                 "name":"cloud_5",
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "rotation":0,
                 "type":"cloud",
                 "visible":true,
                 "width":66,
                 "x":682,
                 "y":313
                }, 
                {
                 "gid":32,
                 "height":39,
                 "id":118,
                 "name":"cloud_5",
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "rotation":0,
                 "type":"cloud",
                 "visible":true,
                 "width":66,
                 "x":828,
                 "y":129
                }, 
                {
                 "gid":1,
                 "height":255,
                 "id":13,
                 "name":"plunger",
                 "properties":[
                        {
                         "name":"stop",
                         "type":"int",
                         "value":535
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"plunger",
                 "visible":true,
                 "width":30,
                 "x":930,
                 "y":550
                }, 
                {
                 "gid":16,
                 "height":26,
                 "id":16,
                 "name":"ball",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":50
                        }],
                 "rotation":0,
                 "type":"ball",
                 "visible":true,
                 "width":26,
                 "x":931.667,
                 "y":290.333
                }, 
                {
                 "gid":17,
                 "height":186,
                 "id":30,
                 "name":"flipper_bumper_left",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":55,
                 "x":373,
                 "y":370.5
                }, 
                {
                 "gid":18,
                 "height":186,
                 "id":31,
                 "name":"flipper_bumper_right",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":55,
                 "x":748.5,
                 "y":382
                }, 
                {
                 "gid":15,
                 "height":95,
                 "id":32,
                 "name":"circle_bumper_red",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":100
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"circle_bumper",
                 "visible":true,
                 "width":94,
                 "x":691,
                 "y":164.167
                }, 
                {
                 "gid":12,
                 "height":95,
                 "id":34,
                 "name":"circle_bumper_yellow",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":100
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"circle_bumper",
                 "visible":true,
                 "width":94,
                 "x":620.833,
                 "y":288.667
                }, 
                {
                 "gid":13,
                 "height":95,
                 "id":35,
                 "name":"circle_bumper_green",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":100
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"circle_bumper",
                 "visible":true,
                 "width":94,
                 "x":414.5,
                 "y":108.333
                }, 
                {
                 "gid":20,
                 "height":310.5,
                 "id":48,
                 "name":"drain_rail_right",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":129.5,
                 "x":722.5,
                 "y":500.5
                }, 
                {
                 "gid":19,
                 "height":324,
                 "id":49,
                 "name":"drain_rail_left",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":138.5,
                 "x":326.636,
                 "y":502.182
                }, 
                {
                 "gid":21,
                 "height":26,
                 "id":58,
                 "name":"lane_trigger",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"trigger",
                 "visible":true,
                 "width":5,
                 "x":816.18,
                 "y":242.818
                }, 
                {
                 "gid":23,
                 "height":13.5454,
                 "id":73,
                 "name":"rotating_gate",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":75
                        }],
                 "rotation":0,
                 "type":"rotating_gate",
                 "visible":true,
                 "width":26.5455,
                 "x":345.091,
                 "y":243.727
                }, 
                {
                 "gid":21,
                 "height":5.51376,
                 "id":92,
                 "name":"light_trigger",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"targ_light",
                         "type":"object",
                         "value":91
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"trigger",
                 "visible":true,
                 "width":2.68293,
                 "x":551.959,
                 "y":130
                }, 
                {
                 "gid":21,
                 "height":5.51,
                 "id":94,
                 "name":"light_trigger",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"targ_light",
                         "type":"object",
                         "value":90
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"trigger",
                 "visible":true,
                 "width":2.68293,
                 "x":585.323,
                 "y":130
                }, 
                {
                 "gid":21,
                 "height":5.51,
                 "id":97,
                 "name":"light_trigger",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"targ_light",
                         "type":"object",
                         "value":89
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"trigger",
                 "visible":true,
                 "width":2.68293,
                 "x":618.323,
                 "y":130
                }, 
                {
                 "gid":26,
                 "height":24,
                 "id":89,
                 "name":"letter_light",
                 "properties":[
                        {
                         "name":"bonus",
                         "type":"object",
                         "value":119
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"letter_light",
                 "visible":true,
                 "width":24,
                 "x":607.333,
                 "y":123
                }, 
                {
                 "gid":26,
                 "height":24,
                 "id":90,
                 "name":"letter_light",
                 "properties":[
                        {
                         "name":"bonus",
                         "type":"object",
                         "value":119
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"letter_light",
                 "visible":true,
                 "width":24,
                 "x":574,
                 "y":123.333
                }, 
                {
                 "gid":26,
                 "height":24,
                 "id":91,
                 "name":"letter_light",
                 "properties":[
                        {
                         "name":"bonus",
                         "type":"object",
                         "value":119
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"letter_light",
                 "visible":true,
                 "width":24,
                 "x":541.333,
                 "y":123
                }, 
                {
                 "gid":21,
                 "height":5.51,
                 "id":103,
                 "name":"light_trigger",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"targ_light",
                         "type":"object",
                         "value":104
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"trigger",
                 "visible":true,
                 "width":2.68293,
                 "x":519.073,
                 "y":130.375
                }, 
                {
                 "gid":26,
                 "height":24,
                 "id":104,
                 "name":"letter_light",
                 "properties":[
                        {
                         "name":"bonus",
                         "type":"object",
                         "value":119
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"letter_light",
                 "visible":true,
                 "width":24,
                 "x":508.083,
                 "y":123.375
                }, 
                {
                 "gid":35,
                 "height":24,
                 "id":119,
                 "name":"bonus_light_2x",
                 "properties":[
                        {
                         "name":"bonusMult",
                         "type":"int",
                         "value":2
                        }, 
                        {
                         "name":"bonusTime",
                         "type":"int",
                         "value":60
                        }, 
                        {
                         "name":"requiredLights",
                         "type":"int",
                         "value":4
                        }],
                 "rotation":0,
                 "type":"status_light",
                 "visible":true,
                 "width":24,
                 "x":515.636,
                 "y":400.364
                }, 
                {
                 "gid":36,
                 "height":94,
                 "id":120,
                 "name":"flipper_left_short",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"left_flipper",
                 "visible":true,
                 "width":112,
                 "x":430,
                 "y":538
                }, 
                {
                 "gid":37,
                 "height":94,
                 "id":121,
                 "name":"flipper_right_short",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"right_flipper",
                 "visible":true,
                 "width":112,
                 "x":629.667,
                 "y":539.167
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":3,
         "name":"Collision",
         "objects":[
                {
                 "ellipse":true,
                 "height":95.4154,
                 "id":3,
                 "name":"circle_bumper_green",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":35
                        }, 
                        {
                         "name":"score",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":0,
                 "type":"circle_bumper",
                 "visible":true,
                 "width":94.652,
                 "x":413.784,
                 "y":13.3133
                }, 
                {
                 "ellipse":true,
                 "height":95.4154,
                 "id":4,
                 "name":"circle_bumper_yellow",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":34
                        }, 
                        {
                         "name":"score",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":0,
                 "type":"circle_bumper",
                 "visible":true,
                 "width":94.652,
                 "x":619.894,
                 "y":192.647
                }, 
                {
                 "ellipse":true,
                 "height":95.4154,
                 "id":5,
                 "name":"circle_bumper_red",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":32
                        }, 
                        {
                         "name":"score",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":0,
                 "type":"circle_bumper",
                 "visible":true,
                 "width":94.652,
                 "x":689.909,
                 "y":68.6127
                }, 
                {
                 "height":0,
                 "id":9,
                 "name":"flipper_bumper_left",
                 "polygon":[
                        {
                         "x":0.75,
                         "y":3.76136
                        }, 
                        {
                         "x":0.875,
                         "y":134.75
                        }, 
                        {
                         "x":3.875,
                         "y":138.375
                        }, 
                        {
                         "x":45.25,
                         "y":178.125
                        }, 
                        {
                         "x":55.25,
                         "y":172.75
                        }, 
                        {
                         "x":19.3636,
                         "y":0.659091
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":30
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":0,
                 "x":372,
                 "y":190.5
                }, 
                {
                 "height":0,
                 "id":41,
                 "name":"plunger",
                 "polygon":[
                        {
                         "x":17.75,
                         "y":46.7727
                        }, 
                        {
                         "x":17.75,
                         "y":59.5
                        }, 
                        {
                         "x":47.75,
                         "y":59.5
                        }, 
                        {
                         "x":47.75,
                         "y":46.7727
                        }, 
                        {
                         "x":37.75,
                         "y":46.7727
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":13
                        }],
                 "rotation":0,
                 "type":"plunger",
                 "visible":true,
                 "width":0,
                 "x":912,
                 "y":248.25
                }, 
                {
                 "ellipse":true,
                 "height":26,
                 "id":45,
                 "name":"ball",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":16
                        }],
                 "rotation":0,
                 "type":"ball",
                 "visible":true,
                 "width":26,
                 "x":931.333,
                 "y":264.667
                }, 
                {
                 "height":0,
                 "id":50,
                 "name":"right",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-194.5,
                         "y":195
                        }, 
                        {
                         "x":107.5,
                         "y":194.5
                        }, 
                        {
                         "x":103.736,
                         "y":-484
                        }, 
                        {
                         "x":70.236,
                         "y":-484.5
                        }, 
                        {
                         "x":70.3182,
                         "y":147.682
                        }, 
                        {
                         "x":34.9091,
                         "y":147.318
                        }, 
                        {
                         "x":34.986,
                         "y":-484
                        }, 
                        {
                         "x":-0.5,
                         "y":-484.223
                        }, 
                        {
                         "x":-139.5,
                         "y":-414
                        }, 
                        {
                         "x":0,
                         "y":-299
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":892.5,
                 "y":404.5
                }, 
                {
                 "height":0,
                 "id":51,
                 "name":"drain_rail_right",
                 "polygon":[
                        {
                         "x":2.75534,
                         "y":-1.96639
                        }, 
                        {
                         "x":-17.3586,
                         "y":1.37647
                        }, 
                        {
                         "x":-21.0783,
                         "y":196.04
                        }, 
                        {
                         "x":-150.366,
                         "y":268.894
                        }, 
                        {
                         "x":-83.9748,
                         "y":312.95
                        }, 
                        {
                         "x":-0.413299,
                         "y":199.579
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":48
                        }],
                 "rotation":0,
                 "type":"drain_divider",
                 "visible":true,
                 "width":0,
                 "x":846.161,
                 "y":189.05
                }, 
                {
                 "height":0,
                 "id":52,
                 "name":"drain_rail_left",
                 "polygon":[
                        {
                         "x":0,
                         "y":-0.78298
                        }, 
                        {
                         "x":2.21184,
                         "y":203.024
                        }, 
                        {
                         "x":92.5958,
                         "y":325.702
                        }, 
                        {
                         "x":142.932,
                         "y":276.187
                        }, 
                        {
                         "x":22.7551,
                         "y":194.188
                        }, 
                        {
                         "x":21.8503,
                         "y":2.70484
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":49
                        }],
                 "rotation":0,
                 "type":"drain_divider",
                 "visible":true,
                 "width":0,
                 "x":328,
                 "y":177.298
                }, 
                {
                 "height":0,
                 "id":53,
                 "name":"left",
                 "polygon":[
                        {
                         "x":0,
                         "y":-80
                        }, 
                        {
                         "x":-1,
                         "y":599.5
                        }, 
                        {
                         "x":210.5,
                         "y":598.5
                        }, 
                        {
                         "x":13.5,
                         "y":401.5
                        }, 
                        {
                         "x":14,
                         "y":105.5
                        }, 
                        {
                         "x":153.5,
                         "y":-11
                        }, 
                        {
                         "x":13.0214,
                         "y":-80.4187
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":276.5,
                 "y":0.5
                }, 
                {
                 "height":0,
                 "id":54,
                 "name":"drain",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-0.5,
                         "y":41
                        }, 
                        {
                         "x":312,
                         "y":39
                        }, 
                        {
                         "x":312.5,
                         "y":-0.5
                        }],
                 "rotation":0,
                 "type":"drain",
                 "visible":true,
                 "width":0,
                 "x":443.5,
                 "y":600
                }, 
                {
                 "height":0,
                 "id":55,
                 "name":"flipper_bumper_right",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0.181818,
                         "y":-134.545
                        }, 
                        {
                         "x":-18.7273,
                         "y":-134.545
                        }, 
                        {
                         "x":-54.3636,
                         "y":38
                        }, 
                        {
                         "x":-44.9091,
                         "y":44
                        }, 
                        {
                         "x":-2.18182,
                         "y":3.63636
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":31
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":0,
                 "x":803.273,
                 "y":335.455
                }, 
                {
                 "ellipse":true,
                 "height":26,
                 "id":59,
                 "name":"lane_trigger",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":58
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":26,
                 "x":805.453,
                 "y":216.727
                }, 
                {
                 "height":0,
                 "id":68,
                 "name":"right",
                 "polygon":[
                        {
                         "x":-132,
                         "y":-17
                        }, 
                        {
                         "x":0.5,
                         "y":93
                        }, 
                        {
                         "x":0.5,
                         "y":-84.5
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":893.5,
                 "y":7
                }, 
                {
                 "height":0,
                 "id":69,
                 "name":"left",
                 "polygon":[
                        {
                         "x":86,
                         "y":-63.5
                        }, 
                        {
                         "x":-48,
                         "y":-129.5
                        }, 
                        {
                         "x":-48.5,
                         "y":48
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":335.5,
                 "y":53
                }, 
                {
                 "height":0,
                 "id":75,
                 "name":"rotating_gate",
                 "polygon":[
                        {
                         "x":-0.301653,
                         "y":-0.489669
                        }, 
                        {
                         "x":3.01653,
                         "y":-5.87603
                        }, 
                        {
                         "x":23.0764,
                         "y":-5.54959
                        }, 
                        {
                         "x":26.2438,
                         "y":0
                        }, 
                        {
                         "x":22.4731,
                         "y":8.4876
                        }, 
                        {
                         "x":3.31818,
                         "y":7.99793
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":73
                        }],
                 "rotation":0,
                 "type":"rotating_gate",
                 "visible":true,
                 "width":0,
                 "x":345.029,
                 "y":236.512
                }, 
                {
                 "ellipse":true,
                 "height":13.9513,
                 "id":93,
                 "name":"light_trigger",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":92
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":13.9513,
                 "x":546.203,
                 "y":120
                }, 
                {
                 "ellipse":true,
                 "height":13.9513,
                 "id":95,
                 "name":"light_trigger",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":94
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":13.9513,
                 "x":579.567,
                 "y":120
                }, 
                {
                 "ellipse":true,
                 "height":13.9513,
                 "id":96,
                 "name":"light_trigger",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":97
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":13.9513,
                 "x":612.567,
                 "y":120
                }, 
                {
                 "ellipse":true,
                 "height":13.9513,
                 "id":102,
                 "name":"light_trigger",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":103
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":13.9513,
                 "x":513.317,
                 "y":120.375
                }, 
                {
                 "ellipse":true,
                 "height":19,
                 "id":105,
                 "name":"flipper_bumper_left",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":30
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":19,
                 "x":372.667,
                 "y":184.417
                }, 
                {
                 "ellipse":true,
                 "height":12,
                 "id":106,
                 "name":"flipper_bumper_left",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":30
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":12,
                 "x":415.375,
                 "y":358
                }, 
                {
                 "ellipse":true,
                 "height":19,
                 "id":108,
                 "name":"flipper_bumper_right",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":31
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":19,
                 "x":784.167,
                 "y":194.5
                }, 
                {
                 "ellipse":true,
                 "height":12,
                 "id":109,
                 "name":"flipper_bumper_right",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":31
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":12,
                 "x":748.667,
                 "y":369
                }, 
                {
                 "ellipse":true,
                 "height":50,
                 "id":122,
                 "name":"flipper_left_short",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":120
                        }],
                 "rotation":0,
                 "type":"flipper_base",
                 "visible":true,
                 "width":50,
                 "x":433,
                 "y":450
                }, 
                {
                 "height":0,
                 "id":125,
                 "name":"flipper_left_short",
                 "polygon":[
                        {
                         "x":-1.33225,
                         "y":5.60564
                        }, 
                        {
                         "x":-49.0129,
                         "y":-36.6828
                        }, 
                        {
                         "x":-56.4076,
                         "y":-22.9943
                        }, 
                        {
                         "x":-7.46752,
                         "y":6.16495
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":120
                        }],
                 "rotation":0,
                 "type":"flipper_inner",
                 "visible":true,
                 "width":0,
                 "x":533.416,
                 "y":518.608
                }, 
                {
                 "ellipse":true,
                 "height":16,
                 "id":126,
                 "name":"flipper_left_short",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":120
                        }],
                 "rotation":0,
                 "type":"flipper_tip",
                 "visible":true,
                 "width":16,
                 "x":522.5,
                 "y":516
                }, 
                {
                 "ellipse":true,
                 "height":16,
                 "id":127,
                 "name":"flipper_right_short",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":121
                        }],
                 "rotation":0,
                 "type":"flipper_tip",
                 "visible":true,
                 "width":16,
                 "x":633,
                 "y":520
                }, 
                {
                 "height":0,
                 "id":130,
                 "name":"flipper_right_short",
                 "polygon":[
                        {
                         "x":-1.33225,
                         "y":-36.1235
                        }, 
                        {
                         "x":-49.0129,
                         "y":6.16495
                        }, 
                        {
                         "x":-56.4076,
                         "y":-7.52355
                        }, 
                        {
                         "x":-7.46752,
                         "y":-36.6828
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":121
                        }],
                 "rotation":180,
                 "type":"flipper_inner",
                 "visible":true,
                 "width":0,
                 "x":638.76,
                 "y":489.982
                }, 
                {
                 "ellipse":true,
                 "height":50,
                 "id":132,
                 "name":"flipper_right_short",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":121
                        }],
                 "rotation":0,
                 "type":"flipper_base",
                 "visible":true,
                 "width":50,
                 "x":692.5,
                 "y":448
                }, 
                {
                 "height":0,
                 "id":133,
                 "name":"flipper_right_short",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":12.5,
                         "y":15
                        }, 
                        {
                         "x":98,
                         "y":-22.5
                        }, 
                        {
                         "x":57.5,
                         "y":-59.25
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":121
                        }],
                 "rotation":0,
                 "type":"flipper",
                 "visible":true,
                 "width":0,
                 "x":636.25,
                 "y":518
                }, 
                {
                 "height":0,
                 "id":136,
                 "name":"flipper_left_short",
                 "polygon":[
                        {
                         "x":0.994422,
                         "y":-1.01877
                        }, 
                        {
                         "x":-55.5239,
                         "y":-55.7333
                        }, 
                        {
                         "x":-69.4559,
                         "y":-29.6369
                        }, 
                        {
                         "x":-5.33544,
                         "y":8.84164
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":120
                        }],
                 "rotation":0,
                 "type":"flipper",
                 "visible":true,
                 "width":0,
                 "x":530.759,
                 "y":512.567
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":7,
 "nextobjectid":137,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.4.3",
 "tileheight":10,
 "tilesets":[
        {
         "columns":0,
         "firstgid":1,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"dynamic",
         "spacing":0,
         "tilecount":36,
         "tileheight":598,
         "tiles":[
                {
                 "id":0,
                 "image":"..\/raw\/img\/backgrounds\/plunger.png",
                 "imageheight":289,
                 "imagewidth":68,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"plunger"
                }, 
                {
                 "id":1,
                 "image":"..\/img\/tables\/flipper_left.png",
                 "imageheight":126,
                 "imagewidth":171,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"left_flipper"
                }, 
                {
                 "id":2,
                 "image":"..\/img\/tables\/flipper_right.png",
                 "imageheight":126,
                 "imagewidth":171,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"right_flipper"
                }, 
                {
                 "id":3,
                 "image":"..\/img\/tables\/plunger_chute.png",
                 "imageheight":598,
                 "imagewidth":105,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":4,
                 "image":"..\/raw\/img\/backgrounds\/drain_wall_left.png",
                 "imageheight":195,
                 "imagewidth":197,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":5,
                 "image":"..\/raw\/img\/backgrounds\/drain_wall_right.png",
                 "imageheight":195,
                 "imagewidth":197,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":6,
                 "image":"..\/raw\/img\/backgrounds\/vertical_wall.png",
                 "imageheight":598,
                 "imagewidth":14,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":7,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_1.png",
                 "imageheight":86,
                 "imagewidth":52,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":8,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_2.png",
                 "imageheight":52,
                 "imagewidth":52,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":9,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_3.png",
                 "imageheight":52,
                 "imagewidth":52,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":10,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_4.png",
                 "imageheight":86,
                 "imagewidth":52,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":11,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_yellow.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"circle_bumper"
                }, 
                {
                 "id":12,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_green.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"circle_bumper"
                }, 
                {
                 "id":13,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_blue.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"circle_bumper"
                }, 
                {
                 "id":14,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_red.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"circle_bumper"
                }, 
                {
                 "id":15,
                 "image":"..\/raw\/img\/backgrounds\/ball.png",
                 "imageheight":26,
                 "imagewidth":26,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":50
                        }],
                 "type":"ball"
                }, 
                {
                 "id":16,
                 "image":"..\/raw\/img\/backgrounds\/flipper_bumper_left.png",
                 "imageheight":186,
                 "imagewidth":55,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"flipper_bumper"
                }, 
                {
                 "id":17,
                 "image":"..\/raw\/img\/backgrounds\/flipper_bumper_right.png",
                 "imageheight":186,
                 "imagewidth":55,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"flipper_bumper"
                }, 
                {
                 "id":18,
                 "image":"..\/raw\/img\/backgrounds\/drain_rail_left.png",
                 "imageheight":270,
                 "imagewidth":82,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":19,
                 "image":"..\/raw\/img\/backgrounds\/drain_rail_right.png",
                 "imageheight":270,
                 "imagewidth":82,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":20,
                 "image":"..\/raw\/img\/backgrounds\/lane_trigger.png",
                 "imageheight":26,
                 "imagewidth":5,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"trigger"
                }, 
                {
                 "id":22,
                 "image":"..\/raw\/img\/backgrounds\/rotating_gate_provisional.png",
                 "imageheight":9,
                 "imagewidth":20,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":75
                        }]
                }, 
                {
                 "id":23,
                 "image":"..\/img\/tables\/angled_wall_5.png",
                 "imageheight":142,
                 "imagewidth":140,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":24,
                 "image":"..\/img\/tables\/angled_wall_6.png",
                 "imageheight":142,
                 "imagewidth":140,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":25,
                 "image":"..\/img\/tables\/letter_light_unlit.png",
                 "imageheight":24,
                 "imagewidth":24,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":26,
                 "image":"..\/img\/tables\/letter_light_lit.png",
                 "imageheight":24,
                 "imagewidth":24,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":27,
                 "image":"..\/img\/tables\/cloud_1.png",
                 "imageheight":78,
                 "imagewidth":108,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":28,
                 "image":"..\/img\/tables\/cloud_2.png",
                 "imageheight":36,
                 "imagewidth":51,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":15
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":29,
                 "image":"..\/img\/tables\/cloud_3.png",
                 "imageheight":54,
                 "imagewidth":81,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":7
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":30,
                 "image":"..\/img\/tables\/cloud_4.png",
                 "imageheight":66,
                 "imagewidth":108,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":31,
                 "image":"..\/img\/tables\/cloud_5.png",
                 "imageheight":39,
                 "imagewidth":66,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":32,
                 "image":"..\/img\/tables\/cloud_6.png",
                 "imageheight":96,
                 "imagewidth":144,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":3
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":33,
                 "image":"..\/img\/tables\/cloud_7.png",
                 "imageheight":96,
                 "imagewidth":144,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":3
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":34,
                 "image":"..\/img\/tables\/2x_bonus_light_unlit.png",
                 "imageheight":24,
                 "imagewidth":24
                }, 
                {
                 "id":35,
                 "image":"..\/img\/tables\/flipper_left_short.png",
                 "imageheight":94,
                 "imagewidth":112
                }, 
                {
                 "id":36,
                 "image":"..\/img\/tables\/flipper_right_short.png",
                 "imageheight":94,
                 "imagewidth":112
                }],
         "tilewidth":197
        }, 
        {
         "columns":0,
         "firstgid":38,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"cloud_bg",
         "spacing":0,
         "tilecount":2,
         "tileheight":600,
         "tiles":[
                {
                 "id":0,
                 "image":"..\/raw\/img\/backgrounds\/cloud_bg.png",
                 "imageheight":600,
                 "imagewidth":720,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-100
                        }]
                }, 
                {
                 "id":1,
                 "image":"..\/img\/tables\/cloud_bg_top_empty.png",
                 "imageheight":600,
                 "imagewidth":720,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-100
                        }]
                }],
         "tilewidth":720
        }, 
        {
         "columns":0,
         "firstgid":40,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"habitrail",
         "spacing":0,
         "tilecount":3,
         "tileheight":125,
         "tiles":[
                {
                 "id":6,
                 "image":"..\/raw\/img\/backgrounds\/habitrail1.png",
                 "imageheight":75,
                 "imagewidth":36,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "type":"habitrail"
                }, 
                {
                 "id":7,
                 "image":"..\/raw\/img\/backgrounds\/habitrail2.png",
                 "imageheight":125,
                 "imagewidth":36,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "type":"habitrail"
                }, 
                {
                 "id":8,
                 "image":"..\/raw\/img\/backgrounds\/habitrail3.png",
                 "imageheight":75,
                 "imagewidth":36,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "type":"habitrail"
                }],
         "tilewidth":36
        }],
 "tilewidth":10,
 "type":"map",
 "version":1.4,
 "width":100
});