(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("prototype_top",
{ "compressionlevel":-1,
 "editorsettings":
    {
     "export":
        {
         "format":"js",
         "target":"prototype_top.js"
        }
    },
 "height":60,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":5,
         "name":"Fixed",
         "objects":[
                {
                 "gid":26,
                 "height":600,
                 "id":75,
                 "name":"cloud_bg_top",
                 "rotation":0,
                 "type":"",
                 "visible":false,
                 "width":720,
                 "x":279.132,
                 "y":599.714
                }, 
                {
                 "gid":7,
                 "height":598,
                 "id":26,
                 "name":"vertical_wall",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":14,
                 "x":276,
                 "y":598
                }, 
                {
                 "gid":11,
                 "height":86,
                 "id":59,
                 "name":"angled_wall_4",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":52,
                 "x":914,
                 "y":100.333
                }, 
                {
                 "gid":21,
                 "height":14,
                 "id":61,
                 "name":"horizontal_wall",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":598,
                 "x":388,
                 "y":14
                }, 
                {
                 "gid":21,
                 "height":14,
                 "id":62,
                 "name":"horizontal_wall",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":598,
                 "x":278,
                 "y":14
                }, 
                {
                 "gid":10,
                 "height":52,
                 "id":70,
                 "name":"angled_wall_3",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":52,
                 "x":842,
                 "y":467
                }, 
                {
                 "gid":9,
                 "height":52,
                 "id":72,
                 "name":"angled_wall_2",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":52,
                 "x":290.25,
                 "y":465.5
                }, 
                {
                 "gid":33,
                 "height":54,
                 "id":77,
                 "name":"plane_pipe_right",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":39,
                 "x":855,
                 "y":180
                }, 
                {
                 "gid":34,
                 "height":54,
                 "id":78,
                 "name":"plane_pipe_left",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":39,
                 "x":290,
                 "y":180
                }, 
                {
                 "gid":27,
                 "height":48,
                 "id":90,
                 "name":"plane_red",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":51,
                 "x":350,
                 "y":178
                }, 
                {
                 "gid":32,
                 "height":54,
                 "id":91,
                 "name":"ball_catch",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":54,
                 "x":310,
                 "y":80
                }, 
                {
                 "gid":31,
                 "height":24,
                 "id":92,
                 "name":"ball_catch_arrow",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":24,
                 "x":350,
                 "y":90
                }, 
                {
                 "gid":24,
                 "height":125,
                 "id":106,
                 "name":"habitrail2",
                 "rotation":0,
                 "type":"habitrail",
                 "visible":true,
                 "width":36,
                 "x":783.667,
                 "y":184
                }, 
                {
                 "gid":25,
                 "height":75,
                 "id":107,
                 "name":"habitrail3",
                 "rotation":305.886,
                 "type":"habitrail",
                 "visible":true,
                 "width":36,
                 "x":792.497,
                 "y":96.3983
                }, 
                {
                 "gid":24,
                 "height":125,
                 "id":108,
                 "name":"habitrail2",
                 "rotation":269.849,
                 "type":"habitrail",
                 "visible":true,
                 "width":36,
                 "x":750.547,
                 "y":61.0016
                }, 
                {
                 "gid":24,
                 "height":125,
                 "id":110,
                 "name":"habitrail2",
                 "rotation":237.033,
                 "type":"habitrail",
                 "visible":true,
                 "width":36,
                 "x":649.898,
                 "y":44.5914
                }, 
                {
                 "gid":25,
                 "height":75,
                 "id":112,
                 "name":"habitrail3",
                 "rotation":214.686,
                 "type":"habitrail",
                 "visible":true,
                 "width":36,
                 "x":565.475,
                 "y":93.5745
                }, 
                {
                 "gid":25,
                 "height":75,
                 "id":113,
                 "name":"habitrail3",
                 "rotation":185.055,
                 "type":"habitrail",
                 "visible":true,
                 "width":36,
                 "x":539.567,
                 "y":127.065
                }, 
                {
                 "gid":25,
                 "height":75,
                 "id":114,
                 "name":"habitrail3",
                 "rotation":0,
                 "type":"habitrail",
                 "visible":true,
                 "width":36,
                 "x":775,
                 "y":248
                }, 
                {
                 "gid":25,
                 "height":75,
                 "id":115,
                 "name":"habitrail3",
                 "rotation":186.521,
                 "type":"habitrail",
                 "visible":true,
                 "width":36,
                 "x":534.809,
                 "y":180.287
                }, 
                {
                 "gid":7,
                 "height":113,
                 "id":106,
                 "name":"plunger_gate",
                 "rotation":0,
                 "type":"gate",
                 "visible":true,
                 "width":14,
                 "x":894,
                 "y":127
                }, 
                {
                 "gid":22,
                 "height":598,
                 "id":110,
                 "name":"chute_wall",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":34,
                 "x":966,
                 "y":597.5
                }, 
                {
                 "gid":22,
                 "height":598,
                 "id":111,
                 "name":"chute_wall",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":34,
                 "x":894,
                 "y":725
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":4,
         "name":"Dynamic",
         "objects":[
                {
                 "gid":2,
                 "height":124,
                 "id":14,
                 "name":"flipper_left",
                 "rotation":0,
                 "type":"left_flipper",
                 "visible":true,
                 "width":170,
                 "x":292,
                 "y":590
                }, 
                {
                 "gid":3,
                 "height":124,
                 "id":15,
                 "name":"flipper_right",
                 "rotation":0,
                 "type":"right_flipper",
                 "visible":true,
                 "width":170,
                 "x":723,
                 "y":593
                }, 
                {
                 "gid":17,
                 "height":186,
                 "id":30,
                 "name":"flipper_bumper_left",
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":55,
                 "x":322,
                 "y":410.5
                }, 
                {
                 "gid":18,
                 "height":186,
                 "id":31,
                 "name":"flipper_bumper_right",
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":55,
                 "x":807.5,
                 "y":428
                }, 
                {
                 "gid":35,
                 "height":54,
                 "id":93,
                 "name":"circle_bumper_small_red",
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":54,
                 "x":430,
                 "y":120
                }, 
                {
                 "gid":38,
                 "height":54,
                 "id":97,
                 "name":"circle_bumper_small_green",
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":54,
                 "x":711,
                 "y":143.5
                }, 
                {
                 "gid":37,
                 "height":54,
                 "id":100,
                 "name":"circle_bumper_small_blue",
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":54,
                 "x":710,
                 "y":310
                }, 
                {
                 "gid":36,
                 "height":54,
                 "id":101,
                 "name":"circle_bumper_small_yellow",
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":54,
                 "x":430,
                 "y":310
                }, 
                {
                 "gid":39,
                 "height":96,
                 "id":103,
                 "name":"cyclone",
                 "rotation":0,
                 "type":"cyclone",
                 "visible":true,
                 "width":96,
                 "x":550,
                 "y":470
                }, 
                {
                 "gid":23,
                 "height":75,
                 "id":105,
                 "name":"habitrail1",
                 "properties":[
                        {
                         "name":"relatedCollisionObjects",
                         "type":"string",
                         "value":"122,123"
                        }],
                 "rotation":0,
                 "type":"habitrail",
                 "visible":true,
                 "width":36,
                 "x":775.667,
                 "y":309.333
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":3,
         "name":"Collision",
         "objects":[
                {
                 "height":0,
                 "id":9,
                 "name":"flipper_bumper_left",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0.25,
                         "y":134.75
                        }, 
                        {
                         "x":2.5,
                         "y":138.5
                        }, 
                        {
                         "x":45.25,
                         "y":178.25
                        }, 
                        {
                         "x":48.5,
                         "y":179.5
                        }, 
                        {
                         "x":51.25,
                         "y":179.5
                        }, 
                        {
                         "x":54.75,
                         "y":176.25
                        }, 
                        {
                         "x":55.25,
                         "y":172.75
                        }, 
                        {
                         "x":19,
                         "y":-0.25
                        }, 
                        {
                         "x":17,
                         "y":-4
                        }, 
                        {
                         "x":13,
                         "y":-6.25
                        }, 
                        {
                         "x":6,
                         "y":-6.25
                        }, 
                        {
                         "x":2,
                         "y":-4.25
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":0,
                 "x":321,
                 "y":230.5
                }, 
                {
                 "height":0,
                 "id":53,
                 "name":"left",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-0.75,
                         "y":710.5
                        }, 
                        {
                         "x":13.25,
                         "y":710.25
                        }, 
                        {
                         "x":13.6553,
                         "y":464.876
                        }, 
                        {
                         "x":65.454,
                         "y":464.748
                        }, 
                        {
                         "x":13.75,
                         "y":413
                        }, 
                        {
                         "x":13,
                         "y":136.5
                        }, 
                        {
                         "x":13.5,
                         "y":49.5
                        }, 
                        {
                         "x":14,
                         "y":-0.5
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":276.5,
                 "y":0.5
                }, 
                {
                 "height":0,
                 "id":55,
                 "name":"flipper_bumper_right",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0.181818,
                         "y":-134.545
                        }, 
                        {
                         "x":-1.81818,
                         "y":-138.545
                        }, 
                        {
                         "x":-5.81818,
                         "y":-140.545
                        }, 
                        {
                         "x":-12.5455,
                         "y":-140.727
                        }, 
                        {
                         "x":-16.3636,
                         "y":-138.727
                        }, 
                        {
                         "x":-18.7273,
                         "y":-134.545
                        }, 
                        {
                         "x":-54.3636,
                         "y":38
                        }, 
                        {
                         "x":-54.5455,
                         "y":42.3636
                        }, 
                        {
                         "x":-51.6364,
                         "y":45.2727
                        }, 
                        {
                         "x":-48.3636,
                         "y":45.2727
                        }, 
                        {
                         "x":-44.9091,
                         "y":44
                        }, 
                        {
                         "x":-2.18182,
                         "y":3.63636
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":0,
                 "x":862.273,
                 "y":381.455
                }, 
                {
                 "height":0,
                 "id":58,
                 "name":"right",
                 "polygon":[
                        {
                         "x":-73.6667,
                         "y":14.5
                        }, 
                        {
                         "x":-21.4868331,
                         "y":99.876
                        }, 
                        {
                         "x":-19.833333,
                         "y":726.833
                        }, 
                        {
                         "x":12.6667,
                         "y":730.333
                        }, 
                        {
                         "x":14.1667,
                         "y":14
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":986.333,
                 "y":0
                }, 
                {
                 "height":0,
                 "id":60,
                 "name":"inner_right",
                 "polygon":[
                        {
                         "x":20,
                         "y":-1
                        }, 
                        {
                         "x":-14,
                         "y":0.843096
                        }, 
                        {
                         "x":-14.2752,
                         "y":287.915
                        }, 
                        {
                         "x":-66.0833,
                         "y":339.463
                        }, 
                        {
                         "x":-14.8238,
                         "y":339.856
                        }, 
                        {
                         "x":-15,
                         "y":596.912
                        }, 
                        {
                         "x":19,
                         "y":597.333
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":908.333,
                 "y":127.333
                }, 
                {
                 "height":0,
                 "id":63,
                 "name":"top",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-664.333,
                         "y":0.333333
                        }, 
                        {
                         "x":-664.333,
                         "y":13.3333
                        }, 
                        {
                         "x":4.66667,
                         "y":14
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":940,
                 "y":0
                }, 
                {
                 "height":0,
                 "id":64,
                 "name":"flipper_right",
                 "polygon":[
                        {
                         "x":-9.33334,
                         "y":5.66666
                        }, 
                        {
                         "x":-130.789,
                         "y":103.516
                        }, 
                        {
                         "x":-117.515,
                         "y":122.788
                        }, 
                        {
                         "x":23.8484,
                         "y":51.7273
                        }],
                 "rotation":0,
                 "type":"flipper",
                 "visible":true,
                 "width":0,
                 "x":856.219,
                 "y":468.677
                }, 
                {
                 "ellipse":true,
                 "height":24,
                 "id":65,
                 "name":"flipper_right",
                 "rotation":0,
                 "type":"flipper_tip",
                 "visible":true,
                 "width":24,
                 "x":720.348,
                 "y":569.303
                }, 
                {
                 "ellipse":true,
                 "height":55,
                 "id":66,
                 "name":"flipper_right",
                 "rotation":0,
                 "type":"flipper_base",
                 "visible":true,
                 "width":55,
                 "x":835.015,
                 "y":468.636
                }, 
                {
                 "height":0,
                 "id":67,
                 "name":"flipper_left",
                 "polygon":[
                        {
                         "x":2.33333,
                         "y":-2
                        }, 
                        {
                         "x":-123.303,
                         "y":-102.575
                        }, 
                        {
                         "x":-154.242,
                         "y":-54.5455
                        }, 
                        {
                         "x":-11.8485,
                         "y":16.2727
                        }],
                 "rotation":0,
                 "type":"flipper",
                 "visible":true,
                 "width":0,
                 "x":458.234,
                 "y":571.584
                }, 
                {
                 "ellipse":true,
                 "height":24,
                 "id":68,
                 "name":"flipper_left",
                 "rotation":0,
                 "type":"flipper_tip",
                 "visible":true,
                 "width":24,
                 "x":439.416,
                 "y":565.917
                }, 
                {
                 "ellipse":true,
                 "height":55,
                 "id":69,
                 "name":"flipper_left",
                 "rotation":0,
                 "type":"flipper_base",
                 "visible":true,
                 "width":55,
                 "x":292.584,
                 "y":465.417
                }, 
                {
                 "height":0,
                 "id":73,
                 "name":"flipper_left",
                 "polygon":[
                        {
                         "x":-2.91667,
                         "y":10.25
                        }, 
                        {
                         "x":-107.303,
                         "y":-67.075
                        }, 
                        {
                         "x":-123.492,
                         "y":-42.0455
                        }, 
                        {
                         "x":-16.3485,
                         "y":11.2727
                        }],
                 "rotation":0,
                 "type":"flipper_inner",
                 "visible":true,
                 "width":0,
                 "x":458.75,
                 "y":569.5
                }, 
                {
                 "height":0,
                 "id":74,
                 "name":"flipper_right",
                 "polygon":[
                        {
                         "x":-35.6667,
                         "y":58.0833
                        }, 
                        {
                         "x":-126.456,
                         "y":124.766
                        }, 
                        {
                         "x":-116.182,
                         "y":128.121
                        }, 
                        {
                         "x":-17.9849,
                         "y":77.144
                        }],
                 "rotation":0,
                 "type":"flipper_inner",
                 "visible":true,
                 "width":0,
                 "x":854,
                 "y":458.75
                }, 
                {
                 "ellipse":true,
                 "height":53,
                 "id":94,
                 "name":"circle_bumper_small_red",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":150
                        }],
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":53,
                 "x":430,
                 "y":66
                }, 
                {
                 "ellipse":true,
                 "height":53,
                 "id":96,
                 "name":"circle_bumper_small_green",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":150
                        }],
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":53,
                 "x":711,
                 "y":89
                }, 
                {
                 "ellipse":true,
                 "height":53,
                 "id":98,
                 "name":"circle_bumper_small_blue",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":150
                        }],
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":53,
                 "x":710,
                 "y":256
                }, 
                {
                 "ellipse":true,
                 "height":53,
                 "id":102,
                 "name":"circle_bumper_small_yellow",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":150
                        }],
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":53,
                 "x":430,
                 "y":256
                }, 
                {
                 "ellipse":true,
                 "height":96,
                 "id":104,
                 "name":"cyclone",
                 "rotation":0,
                 "type":"cyclone",
                 "visible":true,
                 "width":96,
                 "x":550,
                 "y":373
                }, 
                {
                 "height":0,
                 "id":122,
                 "name":"habitrail",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0,
                         "y":-122
                        }, 
                        {
                         "x":-5,
                         "y":-128
                        }, 
                        {
                         "x":8.66667,
                         "y":-145
                        }, 
                        {
                         "x":9.33333,
                         "y":-239
                        }, 
                        {
                         "x":-48.3333,
                         "y":-275.333
                        }, 
                        {
                         "x":-64.3333,
                         "y":-268.667
                        }, 
                        {
                         "x":-74.6667,
                         "y":-277.333
                        }, 
                        {
                         "x":-176.667,
                         "y":-280
                        }, 
                        {
                         "x":-196,
                         "y":-279.667
                        }, 
                        {
                         "x":-280.333,
                         "y":-231
                        }, 
                        {
                         "x":-311.667,
                         "y":-184.667
                        }, 
                        {
                         "x":-321,
                         "y":-68.3333
                        }, 
                        {
                         "x":-318,
                         "y":-69.6667
                        }, 
                        {
                         "x":-307.333,
                         "y":-182.333
                        }, 
                        {
                         "x":-277.333,
                         "y":-230.333
                        }, 
                        {
                         "x":-193.667,
                         "y":-277.333
                        }, 
                        {
                         "x":-77.6667,
                         "y":-274
                        }, 
                        {
                         "x":-66,
                         "y":-265.667
                        }, 
                        {
                         "x":-49.6667,
                         "y":-271
                        }, 
                        {
                         "x":3,
                         "y":-237.667
                        }, 
                        {
                         "x":4.33333,
                         "y":-147
                        }, 
                        {
                         "x":-7.66667,
                         "y":-129.333
                        }, 
                        {
                         "x":-3.33333,
                         "y":-120.667
                        }, 
                        {
                         "x":-6.33333,
                         "y":-0.666667
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":811.667,
                 "y":305.667
                }, 
                {
                 "height":0,
                 "id":123,
                 "name":"habitrail",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-1.33333,
                         "y":-50
                        }, 
                        {
                         "x":-3.66667,
                         "y":-110.333
                        }, 
                        {
                         "x":5,
                         "y":-139
                        }, 
                        {
                         "x":16.3333,
                         "y":-152.333
                        }, 
                        {
                         "x":17,
                         "y":-218.667
                        }, 
                        {
                         "x":-20.6667,
                         "y":-239.333
                        }, 
                        {
                         "x":-48.6667,
                         "y":-250
                        }, 
                        {
                         "x":-62.3333,
                         "y":-256
                        }, 
                        {
                         "x":-139.333,
                         "y":-249
                        }, 
                        {
                         "x":-158.333,
                         "y":-253.333
                        }, 
                        {
                         "x":-217.667,
                         "y":-216.333
                        }, 
                        {
                         "x":-237.333,
                         "y":-176.667
                        }, 
                        {
                         "x":-241.667,
                         "y":-133.333
                        }, 
                        {
                         "x":-250.333,
                         "y":-78
                        }, 
                        {
                         "x":-255,
                         "y":-66
                        }, 
                        {
                         "x":-263.667,
                         "y":-67.6667
                        }, 
                        {
                         "x":-244,
                         "y":-171.333
                        }, 
                        {
                         "x":-225,
                         "y":-216.667
                        }, 
                        {
                         "x":-163,
                         "y":-257
                        }, 
                        {
                         "x":-67,
                         "y":-259.667
                        }, 
                        {
                         "x":18.6667,
                         "y":-226.333
                        }, 
                        {
                         "x":22.6667,
                         "y":-203.667
                        }, 
                        {
                         "x":23,
                         "y":-153.667
                        }, 
                        {
                         "x":6,
                         "y":-129.333
                        }, 
                        {
                         "x":0.666667,
                         "y":-108.333
                        }, 
                        {
                         "x":3.66667,
                         "y":-2
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":777.333,
                 "y":306.333
                }, 
                {
                 "ellipse":true,
                 "height":13.3333,
                 "id":107,
                 "name":"habitrail1",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":35.3333,
                 "x":777,
                 "y":296.333
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":6,
 "nextobjectid":112,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.4.3",
 "tileheight":10,
 "tilesets":[
        {
         "columns":0,
         "firstgid":1,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"dynamic",
         "spacing":0,
         "tilecount":22,
         "tileheight":598,
         "tiles":[
                {
                 "id":0,
                 "image":"..\/raw\/img\/backgrounds\/plunger.png",
                 "imageheight":289,
                 "imagewidth":68,
                 "type":"plunger"
                }, 
                {
                 "id":1,
                 "image":"..\/raw\/img\/backgrounds\/flipper_left.png",
                 "imageheight":124,
                 "imagewidth":170,
                 "type":"left_flipper"
                }, 
                {
                 "id":2,
                 "image":"..\/raw\/img\/backgrounds\/flipper_right.png",
                 "imageheight":124,
                 "imagewidth":170,
                 "type":"right_flipper"
                }, 
                {
                 "id":3,
                 "image":"..\/img\/tables\/plunger_chute.png",
                 "imageheight":598,
                 "imagewidth":105,
                 "type":"wall"
                }, 
                {
                 "id":4,
                 "image":"..\/raw\/img\/backgrounds\/drain_wall_left.png",
                 "imageheight":195,
                 "imagewidth":197,
                 "type":"wall"
                }, 
                {
                 "id":5,
                 "image":"..\/raw\/img\/backgrounds\/drain_wall_right.png",
                 "imageheight":195,
                 "imagewidth":197,
                 "type":"wall"
                }, 
                {
                 "id":6,
                 "image":"..\/img\/tables\/vertical_wall.png",
                 "imageheight":598,
                 "imagewidth":14,
                 "type":"wall"
                }, 
                {
                 "id":7,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_1.png",
                 "imageheight":86,
                 "imagewidth":52,
                 "type":"wall"
                }, 
                {
                 "id":8,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_2.png",
                 "imageheight":52,
                 "imagewidth":52,
                 "type":"wall"
                }, 
                {
                 "id":9,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_3.png",
                 "imageheight":52,
                 "imagewidth":52,
                 "type":"wall"
                }, 
                {
                 "id":10,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_4.png",
                 "imageheight":86,
                 "imagewidth":52,
                 "type":"wall"
                }, 
                {
                 "id":11,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_yellow.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "type":"circle_bumper"
                }, 
                {
                 "id":12,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_green.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "type":"circle_bumper"
                }, 
                {
                 "id":13,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_blue.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "type":"circle_bumper"
                }, 
                {
                 "id":14,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_red.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "type":"circle_bumper"
                }, 
                {
                 "id":15,
                 "image":"..\/raw\/img\/backgrounds\/ball.png",
                 "imageheight":26,
                 "imagewidth":26,
                 "type":"ball"
                }, 
                {
                 "id":16,
                 "image":"..\/raw\/img\/backgrounds\/flipper_bumper_left.png",
                 "imageheight":186,
                 "imagewidth":55,
                 "type":"flipper_bumper"
                }, 
                {
                 "id":17,
                 "image":"..\/raw\/img\/backgrounds\/flipper_bumper_right.png",
                 "imageheight":186,
                 "imagewidth":55,
                 "type":"flipper_bumper"
                }, 
                {
                 "id":18,
                 "image":"..\/raw\/img\/backgrounds\/drain_rail_left.png",
                 "imageheight":240,
                 "imagewidth":82,
                 "type":"wall"
                }, 
                {
                 "id":19,
                 "image":"..\/raw\/img\/backgrounds\/drain_rail_right.png",
                 "imageheight":240,
                 "imagewidth":82,
                 "type":"wall"
                }, 
                {
                 "id":20,
                 "image":"..\/img\/tables\/horizontal_wall.png",
                 "imageheight":14,
                 "imagewidth":598,
                 "type":"wall"
                }, 
                {
                 "id":21,
                 "image":"..\/img\/tables\/chute_wall.png",
                 "imageheight":598,
                 "imagewidth":34,
                 "type":"wall"
                }],
         "tilewidth":598
        }, 
        {
         "columns":0,
         "firstgid":23,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"habitrail",
         "spacing":0,
         "tilecount":3,
         "tileheight":125,
         "tiles":[
                {
                 "id":0,
                 "image":"..\/raw\/img\/backgrounds\/habitrail1.png",
                 "imageheight":75,
                 "imagewidth":36,
                 "type":"habitrail"
                }, 
                {
                 "id":1,
                 "image":"..\/raw\/img\/backgrounds\/habitrail2.png",
                 "imageheight":125,
                 "imagewidth":36,
                 "type":"habitrail"
                }, 
                {
                 "id":2,
                 "image":"..\/raw\/img\/backgrounds\/habitrail3.png",
                 "imageheight":75,
                 "imagewidth":36,
                 "type":"habitrail"
                }],
         "tilewidth":36
        }, 
        {
         "columns":0,
         "firstgid":26,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"cloud_bg_top",
         "spacing":0,
         "tilecount":14,
         "tileheight":600,
         "tiles":[
                {
                 "id":0,
                 "image":"..\/raw\/img\/backgrounds\/cloud_bg_top.png",
                 "imageheight":600,
                 "imagewidth":720
                }, 
                {
                 "id":1,
                 "image":"..\/img\/tables\/plane_red.png",
                 "imageheight":48,
                 "imagewidth":51
                }, 
                {
                 "id":2,
                 "image":"..\/img\/tables\/plane_blue.png",
                 "imageheight":48,
                 "imagewidth":51
                }, 
                {
                 "id":3,
                 "image":"..\/img\/tables\/plane_green.png",
                 "imageheight":48,
                 "imagewidth":51
                }, 
                {
                 "id":4,
                 "image":"..\/img\/tables\/plane_yellow.png",
                 "imageheight":48,
                 "imagewidth":51
                }, 
                {
                 "id":5,
                 "image":"..\/img\/tables\/ball_catch_arrow.png",
                 "imageheight":24,
                 "imagewidth":24
                }, 
                {
                 "id":6,
                 "image":"..\/img\/tables\/ball_catch.png",
                 "imageheight":54,
                 "imagewidth":54
                }, 
                {
                 "id":7,
                 "image":"..\/img\/tables\/plane_pipe_right.png",
                 "imageheight":54,
                 "imagewidth":39
                }, 
                {
                 "id":8,
                 "image":"..\/img\/tables\/plane_pipe_left.png",
                 "imageheight":54,
                 "imagewidth":39
                }, 
                {
                 "id":9,
                 "image":"..\/img\/tables\/circle_bumper_small_red.png",
                 "imageheight":54,
                 "imagewidth":54
                }, 
                {
                 "id":10,
                 "image":"..\/img\/tables\/circle_bumper_small_yellow.png",
                 "imageheight":54,
                 "imagewidth":54
                }, 
                {
                 "id":11,
                 "image":"..\/img\/tables\/circle_bumper_small_blue.png",
                 "imageheight":54,
                 "imagewidth":54
                }, 
                {
                 "id":12,
                 "image":"..\/img\/tables\/circle_bumper_small_green.png",
                 "imageheight":54,
                 "imagewidth":54
                }, 
                {
                 "id":13,
                 "image":"..\/img\/tables\/cyclone.png",
                 "imageheight":96,
                 "imagewidth":96
                }],
         "tilewidth":720
        }],
 "tilewidth":10,
 "type":"map",
 "version":1.4,
 "width":100
});