(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("prototype_top",
{ "compressionlevel":-1,
 "editorsettings":
    {
     "export":
        {
         "format":"js",
         "target":"prototype_top.js"
        }
    },
 "height":60,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":5,
         "name":"Fixed",
         "objects":[
                {
                 "gid":42,
                 "height":600,
                 "id":151,
                 "name":"cloud_bg_top_empty",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-100
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":false,
                 "width":720,
                 "x":277,
                 "y":598
                }, 
                {
                 "gid":7,
                 "height":598,
                 "id":26,
                 "name":"vertical_wall",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":14,
                 "x":276,
                 "y":598
                }, 
                {
                 "gid":11,
                 "height":86,
                 "id":59,
                 "name":"angled_wall_4",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":52,
                 "x":914,
                 "y":100.333
                }, 
                {
                 "gid":21,
                 "height":14,
                 "id":61,
                 "name":"horizontal_wall",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":598,
                 "x":388,
                 "y":14
                }, 
                {
                 "gid":21,
                 "height":14,
                 "id":62,
                 "name":"horizontal_wall",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":598,
                 "x":278,
                 "y":14
                }, 
                {
                 "gid":10,
                 "height":52,
                 "id":70,
                 "name":"angled_wall_3",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":52,
                 "x":842,
                 "y":467
                }, 
                {
                 "gid":9,
                 "height":52,
                 "id":72,
                 "name":"angled_wall_2",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":52,
                 "x":290.25,
                 "y":465.5
                }, 
                {
                 "gid":28,
                 "height":24,
                 "id":92,
                 "name":"ball_catch_arrow",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":24,
                 "x":350,
                 "y":90
                }, 
                {
                 "gid":22,
                 "height":598,
                 "id":110,
                 "name":"chute_wall",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":34,
                 "x":966,
                 "y":597.5
                }, 
                {
                 "gid":22,
                 "height":598,
                 "id":111,
                 "name":"chute_wall",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":34,
                 "x":894,
                 "y":725
                }, 
                {
                 "gid":30,
                 "height":54,
                 "id":77,
                 "name":"plane_pipe_right",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":30
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":39,
                 "x":855,
                 "y":180
                }, 
                {
                 "gid":31,
                 "height":54,
                 "id":78,
                 "name":"plane_pipe_left",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":30
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":39,
                 "x":290,
                 "y":180
                }, 
                {
                 "gid":45,
                 "height":75,
                 "id":137,
                 "name":"habitrail_small_track",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":0,
                 "type":"habitrail",
                 "visible":true,
                 "width":42,
                 "x":385,
                 "y":128
                }, 
                {
                 "gid":45,
                 "height":75,
                 "id":138,
                 "name":"habitrail_small_track",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":63.6624,
                 "type":"habitrail",
                 "visible":true,
                 "width":42,
                 "x":387.409,
                 "y":50.3171
                }, 
                {
                 "gid":46,
                 "height":125,
                 "id":139,
                 "name":"habitrail_track",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":89.4813,
                 "type":"habitrail",
                 "visible":true,
                 "width":42,
                 "x":456.646,
                 "y":17.4
                }, 
                {
                 "gid":46,
                 "height":125,
                 "id":140,
                 "name":"habitrail_track",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":89.7657,
                 "type":"habitrail",
                 "visible":true,
                 "width":42,
                 "x":581.081,
                 "y":17.0891
                }, 
                {
                 "gid":45,
                 "height":75,
                 "id":141,
                 "name":"habitrail_small_track",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":105.005,
                 "type":"habitrail",
                 "visible":true,
                 "width":42,
                 "x":703.882,
                 "y":15.507
                }, 
                {
                 "gid":45,
                 "height":75,
                 "id":142,
                 "name":"habitrail_small_track",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":134.164,
                 "type":"habitrail",
                 "visible":true,
                 "width":42,
                 "x":772.063,
                 "y":32.6423
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":4,
         "name":"Dynamic",
         "objects":[
                {
                 "gid":37,
                 "height":78,
                 "id":153,
                 "name":"cloud_1",
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "rotation":0,
                 "type":"cloud",
                 "visible":true,
                 "width":108,
                 "x":325,
                 "y":143
                }, 
                {
                 "gid":39,
                 "height":54,
                 "id":154,
                 "name":"cloud_3",
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":7
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "rotation":0,
                 "type":"cloud",
                 "visible":true,
                 "width":81,
                 "x":544,
                 "y":196
                }, 
                {
                 "gid":38,
                 "height":36,
                 "id":155,
                 "name":"cloud_2",
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":15
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "rotation":0,
                 "type":"cloud",
                 "visible":true,
                 "width":51,
                 "x":346,
                 "y":278
                }, 
                {
                 "gid":41,
                 "height":39,
                 "id":156,
                 "name":"cloud_5",
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "rotation":0,
                 "type":"cloud",
                 "visible":true,
                 "width":66,
                 "x":820,
                 "y":156
                }, 
                {
                 "gid":40,
                 "height":66,
                 "id":157,
                 "name":"cloud_4",
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "rotation":0,
                 "type":"cloud",
                 "visible":true,
                 "width":108,
                 "x":686,
                 "y":388
                }, 
                {
                 "gid":41,
                 "height":39,
                 "id":158,
                 "name":"cloud_5",
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "rotation":0,
                 "type":"cloud",
                 "visible":true,
                 "width":66,
                 "x":334,
                 "y":490
                }, 
                {
                 "gid":38,
                 "height":36,
                 "id":159,
                 "name":"cloud_2",
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":15
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "rotation":0,
                 "type":"cloud",
                 "visible":true,
                 "width":51,
                 "x":567,
                 "y":521
                }, 
                {
                 "gid":2,
                 "height":124,
                 "id":14,
                 "name":"flipper_left",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"left_flipper",
                 "visible":true,
                 "width":170,
                 "x":299,
                 "y":586
                }, 
                {
                 "gid":3,
                 "height":124,
                 "id":15,
                 "name":"flipper_right",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"right_flipper",
                 "visible":true,
                 "width":170,
                 "x":713,
                 "y":588
                }, 
                {
                 "gid":17,
                 "height":186,
                 "id":30,
                 "name":"flipper_bumper_left",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":55,
                 "x":322,
                 "y":410.5
                }, 
                {
                 "gid":18,
                 "height":186,
                 "id":31,
                 "name":"flipper_bumper_right",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":55,
                 "x":807.5,
                 "y":428
                }, 
                {
                 "gid":32,
                 "height":54,
                 "id":93,
                 "name":"circle_bumper_small_red",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":150
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":54,
                 "x":453.333,
                 "y":129.667
                }, 
                {
                 "gid":35,
                 "height":54,
                 "id":97,
                 "name":"circle_bumper_small_green",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":150
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":54,
                 "x":711,
                 "y":143.5
                }, 
                {
                 "gid":34,
                 "height":54,
                 "id":100,
                 "name":"circle_bumper_small_blue",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":150
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":54,
                 "x":710,
                 "y":310
                }, 
                {
                 "gid":33,
                 "height":54,
                 "id":101,
                 "name":"circle_bumper_small_yellow",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":150
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":54,
                 "x":430,
                 "y":310
                }, 
                {
                 "gid":36,
                 "height":96,
                 "id":103,
                 "name":"cyclone",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"cyclone",
                 "visible":true,
                 "width":96,
                 "x":550,
                 "y":470
                }, 
                {
                 "gid":7,
                 "height":113,
                 "id":106,
                 "name":"plunger_gate",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"gate",
                 "visible":true,
                 "width":14,
                 "x":894,
                 "y":127
                }, 
                {
                 "gid":44,
                 "height":75,
                 "id":136,
                 "name":"habitrail_gateway",
                 "properties":[
                        {
                         "name":"relatedCollisionObjects",
                         "type":"string",
                         "value":"132,133"
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":320.447,
                 "type":"habitrail",
                 "visible":true,
                 "width":42,
                 "x":438.021,
                 "y":188.12
                }, 
                {
                 "gid":34,
                 "height":54,
                 "id":144,
                 "name":"circle_bumper_small_blue",
                 "properties":[
                        {
                         "name":"score",
                         "type":"int",
                         "value":150
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":54,
                 "x":568.333,
                 "y":127.667
                }, 
                {
                 "gid":29,
                 "height":54,
                 "id":91,
                 "name":"ball_catch",
                 "properties":[
                        {
                         "name":"ball_catch",
                         "type":"object",
                         "value":149
                        }, 
                        {
                         "name":"score",
                         "type":"int",
                         "value":100
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"trigger",
                 "visible":true,
                 "width":54,
                 "x":307,
                 "y":78.6667
                }, 
                {
                 "gid":24,
                 "height":48,
                 "id":90,
                 "name":"plane_red",
                 "properties":[
                        {
                         "name":"SpawnX",
                         "type":"int",
                         "value":290
                        }, 
                        {
                         "name":"color",
                         "type":"string",
                         "value":"plane_red"
                        }, 
                        {
                         "name":"maxX",
                         "type":"int",
                         "value":860
                        }, 
                        {
                         "name":"score",
                         "type":"int",
                         "value":200
                        }, 
                        {
                         "name":"spawnX",
                         "type":"int",
                         "value":290
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":25
                        }],
                 "rotation":0,
                 "type":"plane",
                 "visible":true,
                 "width":51,
                 "x":289,
                 "y":175
                }, 
                {
                 "gid":43,
                 "height":54,
                 "id":160,
                 "name":"spawner_plane",
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "rotation":0,
                 "type":"spawner",
                 "visible":true,
                 "width":54,
                 "x":572,
                 "y":306.5
                }, 
                {
                 "gid":45,
                 "height":75,
                 "id":142,
                 "name":"habitrail_gateway",
                 "properties":[
                        {
                         "name":"relatedCollisionObjects",
                         "type":"string",
                         "value":"132,133"
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "rotation":134.164,
                 "type":"habitrail",
                 "visible":true,
                 "width":42,
                 "x":772.063,
                 "y":32.6423
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":3,
         "name":"Collision",
         "objects":[
                {
                 "height":0,
                 "id":9,
                 "name":"flipper_bumper_left",
                 "polygon":[
                        {
                         "x":0.75,
                         "y":0.75
                        }, 
                        {
                         "x":0.25,
                         "y":134.75
                        }, 
                        {
                         "x":2.5,
                         "y":138.5
                        }, 
                        {
                         "x":46.3409,
                         "y":178.795
                        }, 
                        {
                         "x":55.8864,
                         "y":173.75
                        }, 
                        {
                         "x":19,
                         "y":-0.25
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":30
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":0,
                 "x":321,
                 "y":230.5
                }, 
                {
                 "height":0,
                 "id":53,
                 "name":"left",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-0.75,
                         "y":710.5
                        }, 
                        {
                         "x":13.25,
                         "y":710.25
                        }, 
                        {
                         "x":13.6553,
                         "y":464.876
                        }, 
                        {
                         "x":65.454,
                         "y":464.748
                        }, 
                        {
                         "x":13.75,
                         "y":413
                        }, 
                        {
                         "x":13,
                         "y":136.5
                        }, 
                        {
                         "x":13.5,
                         "y":49.5
                        }, 
                        {
                         "x":14,
                         "y":-0.5
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":276.5,
                 "y":0.5
                }, 
                {
                 "height":0,
                 "id":55,
                 "name":"flipper_bumper_right",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0.0909089,
                         "y":-131.727
                        }, 
                        {
                         "x":-18.4546,
                         "y":-134.09
                        }, 
                        {
                         "x":-54.3636,
                         "y":38.7273
                        }, 
                        {
                         "x":-44.4546,
                         "y":44.6364
                        }, 
                        {
                         "x":-2.18182,
                         "y":3.63636
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":31
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":0,
                 "x":862.273,
                 "y":381.455
                }, 
                {
                 "height":0,
                 "id":58,
                 "name":"right",
                 "polygon":[
                        {
                         "x":-73.6667,
                         "y":14.5
                        }, 
                        {
                         "x":-21.4868,
                         "y":99.876
                        }, 
                        {
                         "x":-19.8333,
                         "y":726.833
                        }, 
                        {
                         "x":12.6667,
                         "y":730.333
                        }, 
                        {
                         "x":14.1667,
                         "y":14
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":986.333,
                 "y":0
                }, 
                {
                 "height":0,
                 "id":60,
                 "name":"inner_right",
                 "polygon":[
                        {
                         "x":20,
                         "y":-1
                        }, 
                        {
                         "x":-14,
                         "y":0.843096
                        }, 
                        {
                         "x":-14.2752,
                         "y":287.915
                        }, 
                        {
                         "x":-69.3958,
                         "y":341.151
                        }, 
                        {
                         "x":-14.8238,
                         "y":339.856
                        }, 
                        {
                         "x":-15,
                         "y":596.912
                        }, 
                        {
                         "x":19,
                         "y":597.333
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":908.333,
                 "y":127.333
                }, 
                {
                 "height":0,
                 "id":63,
                 "name":"top",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-664.333,
                         "y":0.333333
                        }, 
                        {
                         "x":-664.333,
                         "y":13.3333
                        }, 
                        {
                         "x":4.66667,
                         "y":14
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":940,
                 "y":0
                }, 
                {
                 "height":0,
                 "id":64,
                 "name":"flipper_right",
                 "polygon":[
                        {
                         "x":-9.52084,
                         "y":4.91666
                        }, 
                        {
                         "x":-132.414,
                         "y":104.016
                        }, 
                        {
                         "x":-117.515,
                         "y":122.788
                        }, 
                        {
                         "x":23.8484,
                         "y":51.7273
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":15
                        }],
                 "rotation":0,
                 "type":"flipper",
                 "visible":true,
                 "width":0,
                 "x":848.219,
                 "y":463.677
                }, 
                {
                 "ellipse":true,
                 "height":24,
                 "id":65,
                 "name":"flipper_right",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":15
                        }],
                 "rotation":0,
                 "type":"flipper_tip",
                 "visible":true,
                 "width":24,
                 "x":710.348,
                 "y":564.303
                }, 
                {
                 "ellipse":true,
                 "height":55,
                 "id":66,
                 "name":"flipper_right",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":15
                        }],
                 "rotation":0,
                 "type":"flipper_base",
                 "visible":true,
                 "width":55,
                 "x":827.015,
                 "y":463.636
                }, 
                {
                 "height":0,
                 "id":67,
                 "name":"flipper_left",
                 "polygon":[
                        {
                         "x":2.20833,
                         "y":-1.875
                        }, 
                        {
                         "x":-123.303,
                         "y":-102.575
                        }, 
                        {
                         "x":-154.242,
                         "y":-54.5455
                        }, 
                        {
                         "x":-11.8485,
                         "y":16.2727
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":14
                        }],
                 "rotation":0,
                 "type":"flipper",
                 "visible":true,
                 "width":0,
                 "x":465.234,
                 "y":567.584
                }, 
                {
                 "ellipse":true,
                 "height":24,
                 "id":68,
                 "name":"flipper_left",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":14
                        }],
                 "rotation":0,
                 "type":"flipper_tip",
                 "visible":true,
                 "width":24,
                 "x":446.416,
                 "y":561.917
                }, 
                {
                 "ellipse":true,
                 "height":55,
                 "id":69,
                 "name":"flipper_left",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":14
                        }],
                 "rotation":0,
                 "type":"flipper_base",
                 "visible":true,
                 "width":55,
                 "x":299.584,
                 "y":461.417
                }, 
                {
                 "height":0,
                 "id":73,
                 "name":"flipper_left",
                 "polygon":[
                        {
                         "x":-2.91667,
                         "y":10.25
                        }, 
                        {
                         "x":-107.303,
                         "y":-67.075
                        }, 
                        {
                         "x":-123.492,
                         "y":-42.0455
                        }, 
                        {
                         "x":-16.3485,
                         "y":11.2727
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":14
                        }],
                 "rotation":0,
                 "type":"flipper_inner",
                 "visible":true,
                 "width":0,
                 "x":465.75,
                 "y":565.5
                }, 
                {
                 "height":0,
                 "id":74,
                 "name":"flipper_right",
                 "polygon":[
                        {
                         "x":-35.6667,
                         "y":58.0833
                        }, 
                        {
                         "x":-126.456,
                         "y":124.766
                        }, 
                        {
                         "x":-116.182,
                         "y":128.121
                        }, 
                        {
                         "x":-17.9849,
                         "y":77.144
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":15
                        }],
                 "rotation":0,
                 "type":"flipper_inner",
                 "visible":true,
                 "width":0,
                 "x":844,
                 "y":453.75
                }, 
                {
                 "ellipse":true,
                 "height":53,
                 "id":94,
                 "name":"circle_bumper_small_red",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":93
                        }],
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":53,
                 "x":453.333,
                 "y":75.6667
                }, 
                {
                 "ellipse":true,
                 "height":53,
                 "id":96,
                 "name":"circle_bumper_small_green",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":97
                        }],
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":53,
                 "x":711,
                 "y":89
                }, 
                {
                 "ellipse":true,
                 "height":53,
                 "id":98,
                 "name":"circle_bumper_small_blue",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":100
                        }],
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":53,
                 "x":710,
                 "y":256
                }, 
                {
                 "ellipse":true,
                 "height":53,
                 "id":102,
                 "name":"circle_bumper_small_yellow",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":101
                        }],
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":53,
                 "x":430,
                 "y":256
                }, 
                {
                 "ellipse":true,
                 "height":96,
                 "id":104,
                 "name":"cyclone",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":103
                        }],
                 "rotation":0,
                 "type":"cyclone",
                 "visible":true,
                 "width":96,
                 "x":550,
                 "y":373
                }, 
                {
                 "height":0,
                 "id":115,
                 "name":"right_pipe",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0.166667,
                         "y":-53.6667
                        }, 
                        {
                         "x":-38,
                         "y":-48.8333
                        }, 
                        {
                         "x":-38,
                         "y":-0.5
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":893.5,
                 "y":178.5
                }, 
                {
                 "height":0,
                 "id":116,
                 "name":"left_pipe",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":38,
                         "y":0
                        }, 
                        {
                         "x":37.6667,
                         "y":-49.6667
                        }, 
                        {
                         "x":0.333333,
                         "y":-54.8333
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":290.5,
                 "y":178.5
                }, 
                {
                 "ellipse":true,
                 "height":15.7464,
                 "id":131,
                 "name":"habitrail_gateway",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":136
                        }],
                 "rotation":319.588,
                 "type":"",
                 "visible":true,
                 "width":43.3333,
                 "x":432.279,
                 "y":180.968
                }, 
                {
                 "height":0,
                 "id":132,
                 "name":"habitrail",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-49.3333,
                         "y":-57.3333
                        }, 
                        {
                         "x":-48.6667,
                         "y":-130.667
                        }, 
                        {
                         "x":16.3333,
                         "y":-166.333
                        }, 
                        {
                         "x":264.333,
                         "y":-168.333
                        }, 
                        {
                         "x":336.333,
                         "y":-154.667
                        }, 
                        {
                         "x":391,
                         "y":-102
                        }, 
                        {
                         "x":389,
                         "y":-101
                        }, 
                        {
                         "x":335,
                         "y":-152.333
                        }, 
                        {
                         "x":269,
                         "y":-164.667
                        }, 
                        {
                         "x":19.3333,
                         "y":-163.667
                        }, 
                        {
                         "x":-44.6667,
                         "y":-129.667
                        }, 
                        {
                         "x":-45,
                         "y":-58.3333
                        }, 
                        {
                         "x":1.33333,
                         "y":-7
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":435,
                 "y":185.667
                }, 
                {
                 "height":0,
                 "id":133,
                 "name":"habitrail",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-44,
                         "y":-51
                        }, 
                        {
                         "x":-44.3333,
                         "y":-80
                        }, 
                        {
                         "x":-3.66667,
                         "y":-99
                        }, 
                        {
                         "x":224.667,
                         "y":-100.333
                        }, 
                        {
                         "x":278.333,
                         "y":-87.3333
                        }, 
                        {
                         "x":324.667,
                         "y":-45.3333
                        }, 
                        {
                         "x":327.667,
                         "y":-47
                        }, 
                        {
                         "x":277,
                         "y":-90.3333
                        }, 
                        {
                         "x":226.333,
                         "y":-102.667
                        }, 
                        {
                         "x":-1.66667,
                         "y":-102.667
                        }, 
                        {
                         "x":-46,
                         "y":-81.3333
                        }, 
                        {
                         "x":-45.6667,
                         "y":-44.6667
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":471.333,
                 "y":158
                }, 
                {
                 "height":0,
                 "id":135,
                 "name":"plunger_gate",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0.666667,
                         "y":112
                        }, 
                        {
                         "x":15.3333,
                         "y":112
                        }, 
                        {
                         "x":14.6667,
                         "y":-0.666667
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":106
                        }],
                 "rotation":0,
                 "type":"gate",
                 "visible":true,
                 "width":0,
                 "x":894,
                 "y":13
                }, 
                {
                 "ellipse":true,
                 "height":53,
                 "id":143,
                 "name":"circle_bumper_small_blue",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":144
                        }],
                 "rotation":0,
                 "type":"circle_bumper_small",
                 "visible":true,
                 "width":53,
                 "x":568.333,
                 "y":73.6667
                }, 
                {
                 "ellipse":true,
                 "height":19,
                 "id":145,
                 "name":"flipper_bumper_left",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":30
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":19,
                 "x":321.75,
                 "y":224
                }, 
                {
                 "ellipse":true,
                 "height":12,
                 "id":146,
                 "name":"flipper_bumper_left",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":30
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":12,
                 "x":364.75,
                 "y":398.25
                }, 
                {
                 "ellipse":true,
                 "height":19,
                 "id":147,
                 "name":"flipper_bumper_right",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":31
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":19,
                 "x":843.25,
                 "y":241.25
                }, 
                {
                 "ellipse":true,
                 "height":12,
                 "id":148,
                 "name":"flipper_bumper_right",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":31
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":12,
                 "x":807.636,
                 "y":415.818
                }, 
                {
                 "ellipse":true,
                 "height":30,
                 "id":149,
                 "name":"ball_catch",
                 "properties":[
                        {
                         "name":"catcher",
                         "type":"bool",
                         "value":true
                        }, 
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":91
                        }],
                 "rotation":0,
                 "type":"trigger",
                 "visible":true,
                 "width":30,
                 "x":318.333,
                 "y":35.6667
                }, 
                {
                 "ellipse":true,
                 "height":48,
                 "id":150,
                 "name":"plane_red",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":90
                        }],
                 "rotation":0,
                 "type":"plane",
                 "visible":true,
                 "width":48,
                 "x":289.5,
                 "y":126.5
                }, 
                {
                 "height":0,
                 "id":162,
                 "name":"spawner_plane",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":37.5,
                         "y":-0.5
                        }, 
                        {
                         "x":20,
                         "y":36
                        }],
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":160
                        }],
                 "rotation":0,
                 "type":"spawner",
                 "visible":true,
                 "width":0,
                 "x":579,
                 "y":260
                }, 
                {
                 "ellipse":true,
                 "height":21.1183046796248,
                 "id":163,
                 "name":"habitrail_gateway",
                 "properties":[
                        {
                         "name":"dynObjConn",
                         "type":"object",
                         "value":142
                        }],
                 "rotation":320.180410924002,
                 "type":"",
                 "visible":true,
                 "width":44.9341623675331,
                 "x":786.607250797247,
                 "y":104.3936320943
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":false,
         "x":0,
         "y":0
        }],
 "nextlayerid":6,
 "nextobjectid":164,
 "orientation":"orthogonal",
 "properties":[
        {
         "name":"maxX",
         "type":"int",
         "value":1000
        }, 
        {
         "name":"minX",
         "type":"int",
         "value":275
        }],
 "renderorder":"right-down",
 "tiledversion":"1.4.3",
 "tileheight":10,
 "tilesets":[
        {
         "columns":0,
         "firstgid":1,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"dynamic",
         "spacing":0,
         "tilecount":22,
         "tileheight":598,
         "tiles":[
                {
                 "id":0,
                 "image":"..\/raw\/img\/backgrounds\/plunger.png",
                 "imageheight":289,
                 "imagewidth":68,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"plunger"
                }, 
                {
                 "id":1,
                 "image":"..\/raw\/img\/backgrounds\/flipper_left.png",
                 "imageheight":124,
                 "imagewidth":170,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"left_flipper"
                }, 
                {
                 "id":2,
                 "image":"..\/raw\/img\/backgrounds\/flipper_right.png",
                 "imageheight":124,
                 "imagewidth":170,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"right_flipper"
                }, 
                {
                 "id":3,
                 "image":"..\/img\/tables\/plunger_chute.png",
                 "imageheight":598,
                 "imagewidth":105,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":4,
                 "image":"..\/raw\/img\/backgrounds\/drain_wall_left.png",
                 "imageheight":195,
                 "imagewidth":197,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":5,
                 "image":"..\/raw\/img\/backgrounds\/drain_wall_right.png",
                 "imageheight":195,
                 "imagewidth":197,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":6,
                 "image":"..\/img\/tables\/vertical_wall.png",
                 "imageheight":598,
                 "imagewidth":14,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":7,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_1.png",
                 "imageheight":86,
                 "imagewidth":52,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":8,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_2.png",
                 "imageheight":52,
                 "imagewidth":52,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":9,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_3.png",
                 "imageheight":52,
                 "imagewidth":52,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":10,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_4.png",
                 "imageheight":86,
                 "imagewidth":52,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":11,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_yellow.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"circle_bumper"
                }, 
                {
                 "id":12,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_green.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"circle_bumper"
                }, 
                {
                 "id":13,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_blue.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"circle_bumper"
                }, 
                {
                 "id":14,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_red.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"circle_bumper"
                }, 
                {
                 "id":15,
                 "image":"..\/raw\/img\/backgrounds\/ball.png",
                 "imageheight":26,
                 "imagewidth":26,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":50
                        }],
                 "type":"ball"
                }, 
                {
                 "id":16,
                 "image":"..\/raw\/img\/backgrounds\/flipper_bumper_left.png",
                 "imageheight":186,
                 "imagewidth":55,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"flipper_bumper"
                }, 
                {
                 "id":17,
                 "image":"..\/raw\/img\/backgrounds\/flipper_bumper_right.png",
                 "imageheight":186,
                 "imagewidth":55,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"flipper_bumper"
                }, 
                {
                 "id":18,
                 "image":"..\/raw\/img\/backgrounds\/drain_rail_left.png",
                 "imageheight":270,
                 "imagewidth":82,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":19,
                 "image":"..\/raw\/img\/backgrounds\/drain_rail_right.png",
                 "imageheight":270,
                 "imagewidth":82,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":20,
                 "image":"..\/img\/tables\/horizontal_wall.png",
                 "imageheight":14,
                 "imagewidth":598,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }, 
                {
                 "id":21,
                 "image":"..\/img\/tables\/chute_wall.png",
                 "imageheight":598,
                 "imagewidth":34,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"wall"
                }],
         "tilewidth":598
        }, 
        {
         "columns":0,
         "firstgid":23,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"cloud_bg_top",
         "spacing":0,
         "tilecount":21,
         "tileheight":600,
         "tiles":[
                {
                 "id":0,
                 "image":"..\/raw\/img\/backgrounds\/cloud_bg_top.png",
                 "imageheight":600,
                 "imagewidth":720,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-100
                        }]
                }, 
                {
                 "id":1,
                 "image":"..\/img\/tables\/plane_red.png",
                 "imageheight":48,
                 "imagewidth":51,
                 "properties":[
                        {
                         "name":"color",
                         "type":"string",
                         "value":"plane_red"
                        }, 
                        {
                         "name":"maxX",
                         "type":"int",
                         "value":860
                        }, 
                        {
                         "name":"spawnX",
                         "type":"int",
                         "value":290
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":25
                        }],
                 "type":"plane"
                }, 
                {
                 "id":2,
                 "image":"..\/img\/tables\/plane_blue.png",
                 "imageheight":48,
                 "imagewidth":51,
                 "properties":[
                        {
                         "name":"color",
                         "type":"string",
                         "value":"plane_blue"
                        }, 
                        {
                         "name":"maxX",
                         "type":"int",
                         "value":860
                        }, 
                        {
                         "name":"spawnX",
                         "type":"int",
                         "value":290
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":25
                        }],
                 "type":"plane"
                }, 
                {
                 "id":3,
                 "image":"..\/img\/tables\/plane_green.png",
                 "imageheight":48,
                 "imagewidth":51,
                 "properties":[
                        {
                         "name":"color",
                         "type":"string",
                         "value":"plane_green"
                        }, 
                        {
                         "name":"maxX",
                         "type":"int",
                         "value":860
                        }, 
                        {
                         "name":"spawnX",
                         "type":"int",
                         "value":290
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":25
                        }],
                 "type":"plane"
                }, 
                {
                 "id":4,
                 "image":"..\/img\/tables\/plane_yellow.png",
                 "imageheight":48,
                 "imagewidth":51,
                 "properties":[
                        {
                         "name":"color",
                         "type":"string",
                         "value":"plane_yellow"
                        }, 
                        {
                         "name":"maxX",
                         "type":"int",
                         "value":860
                        }, 
                        {
                         "name":"spawnX",
                         "type":"int",
                         "value":290
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":25
                        }],
                 "type":"plane"
                }, 
                {
                 "id":5,
                 "image":"..\/img\/tables\/ball_catch_arrow.png",
                 "imageheight":24,
                 "imagewidth":24,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":6,
                 "image":"..\/img\/tables\/ball_catch.png",
                 "imageheight":54,
                 "imagewidth":54,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }],
                 "type":"trigger"
                }, 
                {
                 "id":7,
                 "image":"..\/img\/tables\/plane_pipe_right.png",
                 "imageheight":54,
                 "imagewidth":39,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":30
                        }]
                }, 
                {
                 "id":8,
                 "image":"..\/img\/tables\/plane_pipe_left.png",
                 "imageheight":54,
                 "imagewidth":39,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":30
                        }]
                }, 
                {
                 "id":9,
                 "image":"..\/img\/tables\/circle_bumper_small_red.png",
                 "imageheight":54,
                 "imagewidth":54,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":10,
                 "image":"..\/img\/tables\/circle_bumper_small_yellow.png",
                 "imageheight":54,
                 "imagewidth":54,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":11,
                 "image":"..\/img\/tables\/circle_bumper_small_blue.png",
                 "imageheight":54,
                 "imagewidth":54,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":12,
                 "image":"..\/img\/tables\/circle_bumper_small_green.png",
                 "imageheight":54,
                 "imagewidth":54,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":13,
                 "image":"..\/img\/tables\/cyclone.png",
                 "imageheight":96,
                 "imagewidth":96,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }, 
                {
                 "id":14,
                 "image":"..\/img\/tables\/cloud_1.png",
                 "imageheight":78,
                 "imagewidth":108,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":10
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":15,
                 "image":"..\/img\/tables\/cloud_2.png",
                 "imageheight":36,
                 "imagewidth":51,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":15
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":16,
                 "image":"..\/img\/tables\/cloud_3.png",
                 "imageheight":54,
                 "imagewidth":81,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":7
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":17,
                 "image":"..\/img\/tables\/cloud_4.png",
                 "imageheight":66,
                 "imagewidth":108,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":5
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":18,
                 "image":"..\/img\/tables\/cloud_5.png",
                 "imageheight":39,
                 "imagewidth":66,
                 "properties":[
                        {
                         "name":"xVelocity",
                         "type":"int",
                         "value":25
                        }, 
                        {
                         "name":"yVelocity",
                         "type":"int",
                         "value":0
                        }, 
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-80
                        }],
                 "type":"cloud"
                }, 
                {
                 "id":19,
                 "image":"..\/img\/tables\/cloud_bg_top_empty.png",
                 "imageheight":600,
                 "imagewidth":720,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":-100
                        }]
                }, 
                {
                 "id":20,
                 "image":"..\/img\/tables\/spawner_plane.png",
                 "imageheight":54,
                 "imagewidth":54,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":0
                        }]
                }],
         "tilewidth":720
        }, 
        {
         "columns":0,
         "firstgid":44,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"habitrail",
         "spacing":0,
         "tilecount":3,
         "tileheight":125,
         "tiles":[
                {
                 "id":0,
                 "image":"..\/img\/tables\/habitrail_gateway.png",
                 "imageheight":75,
                 "imagewidth":42,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "type":"habitrail"
                }, 
                {
                 "id":1,
                 "image":"..\/img\/tables\/habitrail_small_track.png",
                 "imageheight":75,
                 "imagewidth":42,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "type":"habitrail"
                }, 
                {
                 "id":2,
                 "image":"..\/img\/tables\/habitrail_track.png",
                 "imageheight":125,
                 "imagewidth":42,
                 "properties":[
                        {
                         "name":"zOrder",
                         "type":"int",
                         "value":100
                        }],
                 "type":"habitrail"
                }],
         "tilewidth":42
        }],
 "tilewidth":10,
 "type":"map",
 "version":1.4,
 "width":100
});