(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') {TileMaps = {};}
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }}("prototype",
{"compressionlevel":-1,
 "editorsettings":
    {
     "export":
        {
         "format":"js",
         "target":"prototype.js"
        }
    },
 "height":60,
 "infinite":false,
 "layers":[
        {
         "draworder":"topdown",
         "id":5,
         "name":"Fixed",
         "objects":[
                {
                 "gid":4,
                 "height":598,
                 "id":23,
                 "name":"plunger_chute",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":105,
                 "x":693,
                 "y":598
                }, 
                {
                 "gid":6,
                 "height":195,
                 "id":24,
                 "name":"right_drain_wall",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":197,
                 "x":496,
                 "y":600
                }, 
                {
                 "gid":5,
                 "height":195,
                 "id":25,
                 "name":"left_drain_wall",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":197,
                 "x":13,
                 "y":598
                }, 
                {
                 "gid":7,
                 "height":598,
                 "id":26,
                 "name":"vertical_wall",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":14,
                 "x":0,
                 "y":598
                }, 
                {
                 "gid":19,
                 "height":240,
                 "id":27,
                 "name":"drain_left_rail",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":82,
                 "x":69,
                 "y":420
                }, 
                {
                 "gid":20,
                 "height":240,
                 "id":29,
                 "name":"drain_right_rail",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":82,
                 "x":556,
                 "y":419
                }, 
                {
                 "gid":11,
                 "height":86,
                 "id":36,
                 "name":"angled_wall_4",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":52,
                 "x":643,
                 "y":138
                }, 
                {
                 "gid":8,
                 "height":86,
                 "id":37,
                 "name":"angled_wall_1",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":52,
                 "x":14,
                 "y":138
                }, 
                {
                 "gid":10,
                 "height":52,
                 "id":39,
                 "name":"angled_wall_3",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":52,
                 "x":642.666666666667,
                 "y":52.3333333333333
                }, 
                {
                 "gid":9,
                 "height":52,
                 "id":40,
                 "name":"angled_wall_2",
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":52,
                 "x":14,
                 "y":53
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":4,
         "name":"Dynamic",
         "objects":[
                {
                 "gid":1,
                 "height":289,
                 "id":13,
                 "name":"plunger",
                 "rotation":0,
                 "type":"plunger",
                 "visible":true,
                 "width":68,
                 "x":712,
                 "y":552
                }, 
                {
                 "gid":2,
                 "height":124,
                 "id":14,
                 "name":"flipper_left",
                 "rotation":0,
                 "type":"left_flipper",
                 "visible":true,
                 "width":170,
                 "x":130,
                 "y":539
                }, 
                {
                 "gid":3,
                 "height":124,
                 "id":15,
                 "name":"flipper_right",
                 "rotation":0,
                 "type":"right_flipper",
                 "visible":true,
                 "width":170,
                 "x":408,
                 "y":540
                }, 
                {
                 "gid":16,
                 "height":26,
                 "id":16,
                 "name":"ball",
                 "rotation":0,
                 "type":"ball",
                 "visible":true,
                 "width":26,
                 "x":514,
                 "y":85
                }, 
                {
                 "gid":16,
                 "height":26,
                 "id":17,
                 "name":"ball",
                 "rotation":0,
                 "type":"ball",
                 "visible":true,
                 "width":26,
                 "x":9,
                 "y":596
                }, 
                {
                 "gid":16,
                 "height":26,
                 "id":18,
                 "name":"ball",
                 "rotation":0,
                 "type":"ball",
                 "visible":true,
                 "width":26,
                 "x":42,
                 "y":596
                }, 
                {
                 "gid":17,
                 "height":186,
                 "id":30,
                 "name":"flipper_bumper_left",
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":55,
                 "x":130,
                 "y":363.5
                }, 
                {
                 "gid":18,
                 "height":186,
                 "id":31,
                 "name":"flipper_bumper_right",
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":55,
                 "x":524.5,
                 "y":363
                }, 
                {
                 "gid":15,
                 "height":95,
                 "id":32,
                 "name":"circle_bumper_red",
                 "rotation":0,
                 "type":"circle_bumper",
                 "visible":true,
                 "width":94,
                 "x":311,
                 "y":271.5
                }, 
                {
                 "gid":14,
                 "height":95,
                 "id":33,
                 "name":"circle_bumper_blue",
                 "rotation":0,
                 "type":"circle_bumper",
                 "visible":true,
                 "width":94,
                 "x":310.5,
                 "y":98
                }, 
                {
                 "gid":12,
                 "height":95,
                 "id":34,
                 "name":"circle_bumper_yellow",
                 "rotation":0,
                 "type":"circle_bumper",
                 "visible":true,
                 "width":94,
                 "x":405.5,
                 "y":188
                }, 
                {
                 "gid":13,
                 "height":95,
                 "id":35,
                 "name":"circle_bumper_green",
                 "rotation":0,
                 "type":"circle_bumper",
                 "visible":true,
                 "width":94,
                 "x":216.5,
                 "y":187
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":3,
         "name":"Collision",
         "objects":[
                {
                 "ellipse":true,
                 "height":95.4153512698487,
                 "id":1,
                 "name":"circle_bumper_blue",
                 "rotation":0,
                 "type":"circle_bumper",
                 "visible":true,
                 "width":94.65202845969,
                 "x":309.909060924469,
                 "y":2.28996843047637
                }, 
                {
                 "ellipse":true,
                 "height":95.4154,
                 "id":3,
                 "name":"circle_bumper_green",
                 "rotation":0,
                 "type":"circle_bumper",
                 "visible":true,
                 "width":94.652,
                 "x":215.783692314941,
                 "y":91.9803742590586
                }, 
                {
                 "ellipse":true,
                 "height":95.4154,
                 "id":4,
                 "name":"circle_bumper_yellow",
                 "rotation":0,
                 "type":"circle_bumper",
                 "visible":true,
                 "width":94.652,
                 "x":404.561103614004,
                 "y":91.9803742590586
                }, 
                {
                 "ellipse":true,
                 "height":95.4154,
                 "id":5,
                 "name":"circle_bumper_red",
                 "rotation":0,
                 "type":"circle_bumper",
                 "visible":true,
                 "width":94.652,
                 "x":309.909075154314,
                 "y":175.945883376525
                }, 
                {
                 "height":0,
                 "id":6,
                 "name":"right",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":-6,
                         "y":2.75
                        }, 
                        {
                         "x":-6.25,
                         "y":160.75
                        }, 
                        {
                         "x":-76.25,
                         "y":231
                        }, 
                        {
                         "x":-69.5,
                         "y":238.25
                        }, 
                        {
                         "x":3.75,
                         "y":166
                        }, 
                        {
                         "x":4,
                         "y":1.75
                        }],
                 "rotation":0,
                 "type":"drain_divider",
                 "visible":true,
                 "width":0,
                 "x":633.25,
                 "y":179
                }, 
                {
                 "height":0,
                 "id":7,
                 "name":"flipper_bumper_right",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0.25,
                         "y":134.75
                        }, 
                        {
                         "x":-2,
                         "y":139
                        }, 
                        {
                         "x":-45.25,
                         "y":178.75
                        }, 
                        {
                         "x":-48.25,
                         "y":180
                        }, 
                        {
                         "x":-51.5,
                         "y":180
                        }, 
                        {
                         "x":-55,
                         "y":177.25
                        }, 
                        {
                         "x":-55,
                         "y":172.75
                        }, 
                        {
                         "x":-18.75,
                         "y":0
                        }, 
                        {
                         "x":-16.5,
                         "y":-4.5
                        }, 
                        {
                         "x":-12.75,
                         "y":-6.25
                        }, 
                        {
                         "x":-6.5,
                         "y":-6
                        }, 
                        {
                         "x":-2.5,
                         "y":-4.25
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":0,
                 "x":579,
                 "y":183.25
                }, 
                {
                 "height":0,
                 "id":8,
                 "name":"drain",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":310,
                         "y":0.25
                        }, 
                        {
                         "x":310.25,
                         "y":35.25
                        }, 
                        {
                         "x":0,
                         "y":36
                        }],
                 "rotation":0,
                 "type":"drain",
                 "visible":true,
                 "width":0,
                 "x":200,
                 "y":597.75
                }, 
                {
                 "height":0,
                 "id":9,
                 "name":"flipper_bumper_left",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0.25,
                         "y":134.75
                        }, 
                        {
                         "x":2.5,
                         "y":138.5
                        }, 
                        {
                         "x":45.25,
                         "y":178.25
                        }, 
                        {
                         "x":48.5,
                         "y":179.5
                        }, 
                        {
                         "x":51.25,
                         "y":179.5
                        }, 
                        {
                         "x":54.75,
                         "y":176.25
                        }, 
                        {
                         "x":55.25,
                         "y":172.75
                        }, 
                        {
                         "x":19,
                         "y":-0.25
                        }, 
                        {
                         "x":17,
                         "y":-4
                        }, 
                        {
                         "x":13,
                         "y":-6.25
                        }, 
                        {
                         "x":6,
                         "y":-6.25
                        }, 
                        {
                         "x":2,
                         "y":-4.25
                        }],
                 "rotation":0,
                 "type":"flipper_bumper",
                 "visible":true,
                 "width":0,
                 "x":129,
                 "y":183.5
                }, 
                {
                 "height":0,
                 "id":10,
                 "name":"left",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":5.5,
                         "y":2.5
                        }, 
                        {
                         "x":6,
                         "y":161
                        }, 
                        {
                         "x":75.5,
                         "y":231
                        }, 
                        {
                         "x":69,
                         "y":238
                        }, 
                        {
                         "x":-3.75,
                         "y":166
                        }, 
                        {
                         "x":-4,
                         "y":1.5
                        }],
                 "rotation":0,
                 "type":"drain_divider",
                 "visible":true,
                 "width":0,
                 "x":73.25,
                 "y":179.25
                }, 
                {
                 "height":0,
                 "id":11,
                 "name":"right",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":0,
                         "y":549
                        }, 
                        {
                         "x":-75.6666666666667,
                         "y":549.333333333333
                        }, 
                        {
                         "x":-76,
                         "y":-0.333333333333333
                        }, 
                        {
                         "x":-89.6666666666667,
                         "y":-0.333333333333333
                        }, 
                        {
                         "x":-141.666666666667,
                         "y":52.3333333333333
                        }, 
                        {
                         "x":-90.6666666666667,
                         "y":135.666666666667
                        }, 
                        {
                         "x":-90.6666666666667,
                         "y":402.666666666667
                        }, 
                        {
                         "x":-285.333333333333,
                         "y":597.666666666667
                        }, 
                        {
                         "x":13.6666666666666,
                         "y":597.666666666667
                        }, 
                        {
                         "x":13.6666666666666,
                         "y":0
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":784,
                 "y":0.333333333333333
                }, 
                {
                 "height":0,
                 "id":12,
                 "name":"left",
                 "polygon":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":51.6666666666667,
                         "y":52
                        }, 
                        {
                         "x":0.333333333333332,
                         "y":136.333333333333
                        }, 
                        {
                         "x":0,
                         "y":402.333333333333
                        }, 
                        {
                         "x":194.666666666667,
                         "y":597.333333333333
                        }, 
                        {
                         "x":-14,
                         "y":596.666666666667
                        }, 
                        {
                         "x":-14,
                         "y":-0.333333333333333
                        }],
                 "rotation":0,
                 "type":"wall",
                 "visible":true,
                 "width":0,
                 "x":14,
                 "y":0.666666666666667
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":6,
 "nextobjectid":41,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.4.3",
 "tileheight":10,
 "tilesets":[
        {
         "columns":0,
         "firstgid":1,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"dynamic",
         "spacing":0,
         "tilecount":20,
         "tileheight":598,
         "tiles":[
                {
                 "id":0,
                 "image":"..\/raw\/img\/backgrounds\/plunger.png",
                 "imageheight":289,
                 "imagewidth":68,
                 "type":"plunger"
                }, 
                {
                 "id":1,
                 "image":"..\/raw\/img\/backgrounds\/flipper_left.png",
                 "imageheight":124,
                 "imagewidth":170,
                 "type":"left_flipper"
                }, 
                {
                 "id":2,
                 "image":"..\/raw\/img\/backgrounds\/flipper_right.png",
                 "imageheight":124,
                 "imagewidth":170,
                 "type":"right_flipper"
                }, 
                {
                 "id":3,
                 "image":"..\/raw\/img\/backgrounds\/plunger_chute.png",
                 "imageheight":598,
                 "imagewidth":105,
                 "type":"wall"
                }, 
                {
                 "id":4,
                 "image":"..\/raw\/img\/backgrounds\/left_drain_wall.png",
                 "imageheight":195,
                 "imagewidth":197,
                 "type":"wall"
                }, 
                {
                 "id":5,
                 "image":"..\/raw\/img\/backgrounds\/right_drain_wall.png",
                 "imageheight":195,
                 "imagewidth":197,
                 "type":"wall"
                }, 
                {
                 "id":6,
                 "image":"..\/raw\/img\/backgrounds\/vertical_wall.png",
                 "imageheight":598,
                 "imagewidth":14
                }, 
                {
                 "id":7,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_1.png",
                 "imageheight":86,
                 "imagewidth":52,
                 "type":"wall"
                }, 
                {
                 "id":8,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_2.png",
                 "imageheight":52,
                 "imagewidth":52,
                 "type":"wall"
                }, 
                {
                 "id":9,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_3.png",
                 "imageheight":52,
                 "imagewidth":52,
                 "type":"wall"
                }, 
                {
                 "id":10,
                 "image":"..\/raw\/img\/backgrounds\/angled_wall_4.png",
                 "imageheight":86,
                 "imagewidth":52,
                 "type":"wall"
                }, 
                {
                 "id":11,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_yellow.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "type":"circle_bumper"
                }, 
                {
                 "id":12,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_green.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "type":"circle_bumper"
                }, 
                {
                 "id":13,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_blue.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "type":"circle_bumper"
                }, 
                {
                 "id":14,
                 "image":"..\/raw\/img\/backgrounds\/circle_bumper_red.png",
                 "imageheight":95,
                 "imagewidth":94,
                 "type":"circle_bumper"
                }, 
                {
                 "id":15,
                 "image":"..\/raw\/img\/backgrounds\/ball.png",
                 "imageheight":26,
                 "imagewidth":26,
                 "type":"ball"
                }, 
                {
                 "id":16,
                 "image":"..\/raw\/img\/backgrounds\/flipper_bumper_left.png",
                 "imageheight":186,
                 "imagewidth":55,
                 "type":"flipper_bumper"
                }, 
                {
                 "id":17,
                 "image":"..\/raw\/img\/backgrounds\/flipper_bumper_right.png",
                 "imageheight":186,
                 "imagewidth":55,
                 "type":"flipper_bumper"
                }, 
                {
                 "id":18,
                 "image":"..\/raw\/img\/backgrounds\/drain_rail_left.png",
                 "imageheight":240,
                 "imagewidth":82,
                 "type":"wall"
                }, 
                {
                 "id":19,
                 "image":"..\/raw\/img\/backgrounds\/drain_rail_right.png",
                 "imageheight":240,
                 "imagewidth":82,
                 "type":"wall"
                }],
         "tilewidth":197
        }],
 "tilewidth":10,
 "type":"map",
 "version":1.4,
 "width":80}));